### PR TITLE
Justin alarm section alarm config filter search

### PR DESCRIPTION
**Pull request by pauljustinhernandez**
Correlates to this ASANA ticket: https://app.asana.com/0/1202364707885489/1202818970595348/f
NOTE: No task/ticket was assigned for this as of the moment. This is just for QI and subject for perusal.

Description:
- Implemented dynamic filter search
- Refrain from copy paste the timeoutMillis field

### CODE REVIEW

**Comment by triveni-codev** [comment]
This has been noticed and thank you for proactively doing this, Jus.

**Comment by triveni-codev** [comment]
Assigning main reviewer task: @chriscodev
This is part of the continuous innovation/improvement of the Alarm section. Does not necessarily need a specific ticket.

**Comment by chriscodev** [comment]
hi @pauljustinhernandez ,

Here are my Review on the PR:

qa1: i tried to change set all dropdown to "Information" and set timeout to 99, cant proceed to success state 

qa2: i tried update all info in dropdown to timeouts and send in email, it was a success but send email is not retrieving the actual data that is being updated

see attached image:

qa1
qa2

**Comment by pauljustinhernandez** [comment]
Hi Tian @chriscodev , below are my response to the issues you have raised;

qa1: Upon checking, no errors encountered on my end, I think it is something to do with your GBOne version just like the previous testing? I sent a clip to you via slack FYR ~ I can't send it here as the file is too big.

qa2: This issue is fine for now, coz the sendEmail property is not yet available in the BE. cc: @triveni-codev

**Comment by chriscodev** [comment]
hi @pauljustinhernandez , LGTM

**Pull request merged**
