### PR TITLE
chrisdev_transportSection_1202878734588543

### PR DESCRIPTION
**Pull request by chriscodev**
1. To able to dirty delete a single Transport Type 
2. To able to dirty delete more than 1 Transport of the same Type
3. To be able to dirty delete more than 1 Transport of different Types
4. To be able to effectively perform a "Big Commit" after No.1/No.2/No.3
5. To be able to add then delete transport

### CODE REVIEW

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking. Here are my concerns while parallel testing with client app:

1. i1: Kindly add a question mark at the end of the question.
2. i1: Every time the Delete Confirmation Box pops out, I am allowed to click on the background that will close the Confirmation Box with a cancel action.
3. i2: I based on the cancel/no of Commit and Revert buttons, seemed like we don't need to inform that a delete confirmation has been cancelled.
4. i3: I have added trans3 and trans4 (uncommitted) and clicked delete button on trans4, the question shows up for trans3.
5. i3: In relation to above, upon clicking OK on the Delete Notification Box, it will delete Trans3 (not Trans4).
6. i4: Adding new transport will trigger to enable the Commit & Revert buttons, however, removing that newly added transport won't disable back the Commit & Revert buttons. Client App does.
7. i5: I have 2 existing transports from server. I have updated the transport just the name and the tsid value then deleted the 2nd transport. When I attempted to commit my changes, that popped out.
8. i5: In relation to above, it also happened when I updated the 2nd transport then deleted that transport ang clicked commit.



i1: 
image

i2: 
image

i3: 
image

i4: 
image

i5: 
image

**Comment by chriscodev** [comment]
hi @darlp5589 ,

new PR updates: 

[DONE] i1: Kindly add a question mark at the end of the question. 

[DONE] i1: Every time the Delete Confirmation Box pops out, I am allowed to click on the background that will close the Confirmation Box with a cancel action.

[DONE] i2: I based on the cancel/no of Commit and Revert buttons, seemed like we don't need to inform that a delete confirmation has been cancelled.

[DONE] i3: I have added trans3 and trans4 (uncommitted) and clicked delete button on trans4, the question shows up for trans3.

[DONE] i3: In relation to above, upon clicking OK on the Delete Notification Box, it will delete Trans3 (not Trans4).

[DONE] i4: Adding new transport will trigger to enable the Commit & Revert buttons, however, removing that newly added transport won't disable back the Commit & Revert buttons. Client App does.

[DONE] i5: I have 2 existing transports from server. I have updated the transport just the name and the tsid value then deleted the 2nd transport. When I attempted to commit my changes, that popped out.

[DONE] i5: In relation to above, it also happened when I updated the 2nd transport then deleted that transport ang clicked commit.


Cheers,
Christian

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking fixes. Here are my concerns which are actually not about the delete feature but I just noticed them along the way while checking along with client app.

1.i1: By the way, while checking fixes, I just noticed based on client app that transport naming is case sensitive. Thus TransA and Transa are treated differently and shouldn't be considered same.
2. This is in relation to the commit/revert buttons being disabled after deleting the newly added transport. Same goes with renaming a transport from server, then eventually revert to original name, it should disable the commit/revert button.


i1: 
image

**Comment by chriscodev** [comment]
hi @darlp5589 , new PR update - https://github.com/triveni-codev/GBWebApp-dev/pull/459/commits/0c713940d205da93eca207828a0918b2ec8e0a4f

[DONE] - 1.i1: By the way, while checking fixes, I just noticed based on client app that transport naming is case sensitive. Thus TransA and Transa are treated differently and shouldn't be considered same.

[DONE] - 2. This is in relation to the commit/revert buttons being disabled after deleting the newly added transport. Same goes with renaming a transport from server, then eventually revert to original name, it should disable the commit/revert button.

**Review by darlp5589 — APPROVED** [review]
Done checking fixes. I have approved this.

**Comment by triveni-codev** [comment]
Commencing merge on this PR after recent update checks

~~~~
Transports Section: Delete Transport(s) development
https://app.asana.com/0/1201468220173184/1202878734588543/f

**Comment by triveni-codev** [comment]
Merging this PR after final clarifications.

Do note that you left this unused variable declaration out as per your request for future use. I hope this does not cause a cascade of unused variables and this needs to be deleted if left unused afterwards.
image

~~~~
Transports Section: Delete Transport(s) development
https://app.asana.com/0/1201468220173184/1202878734588543/f

**Pull request merged**
