### PR TITLE
chrisdev_schedProv_ingestPMCPfix

### PR DESCRIPTION
**Pull request by chriscodev**
This addresses 2 things in Schedule Provider:
1. **Ingest button operability update**: Fix made to ensure that ingest button is actually enabled when needed. Includes changes to modal dynamic table.
2. **PMCP operability update:** Fix made to restore operability of doing a successful "test connection" inside a PMCP schedule provider.
Reference: 
image

### CODE REVIEW

**Comment by triveni-codev** [comment]
Hi @darlp5589 , this is the PR in focus subject for your mainman review. PR details/caption above is revamped.

~~~
@chriscodev

**Comment by darlp5589** [comment]
Got this. Reviewing now.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking changes. Here are my concerns:

i1: Kindly check all those in red marks. 
  -can we change to question mark (?) instead of exclamation point (!)?
  -please change from 'schedule' to 'schedules'
  -add 'the'
i2: Shouldn't ingest 2 selected SPs.  
  
  
i1: 
image

i2: 
image

**Comment by chriscodev** [comment]
hi @darl, 

i have new updates, you may now verfiy in your end

i1: done

for i2: my current java app  can ingest 2 data
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking fixes. I have a concern below:

It shouldn't ingest if one of the 2 SPs aren't committed yet.

image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking fixes. I have concerns:

Considerations: 
SP1 and SP2 are already from server and can be ingested.
SP3 is a newly created one but not committed yet.

i1: Selected SP3 first then selected SP2, the ingest button is enabled.
i2: Selected any of the SP records and unselect all of them, the delete button is still enabaled.
i3: Selected SP1, SP2 then SP3. The ingest button is disabled which is correct but if I unselect the SP3, ingest button should be enabled since both SP1 and SP2 are from server and can be ingested.
i4: Selecting SP3 only, the edit button is disabled.



i1: 
image

i2: 
image

i3: 
image

i4: 
image

**Review by darlp5589 — APPROVED** [review]
This is already approved! 

I have 1 concern though, upon doing a group ingest, can you confirm that all selected SPs are really ingested? I am thinking it only ingests one record but I might be wrong. Please confirm. Thanks!

**Pull request closed without merging**
