### PR TITLE
chrisdev_modalPSIdefault_1203287929531879_v2

### PR DESCRIPTION
**Pull request by chriscodev**
Hi @triveni-codev ,

you may nowcheck this new branch a branch out from master branch:

this is based on this issue:
chrisdev_modalPSIdefault_1203287929531879

this new commit for reusable component of PSIP  and PSI table settings and can be also use in import

You may now check this PR.

Cheers,
Christian

https://app.asana.com/0/0/1203287929531879/1203520537264318/f

### CODE REVIEW

**Comment by triveni-codev** [comment]
Above is an action to the highlighted section below:
https://github.com/triveni-codev/GBWebApp-dev/pull/501#issuecomment-1343698292
image

@chriscodev , I need comprehensive self-check bullet details on the coverage of the fix so that we can avoid dancing around in circles and continue making actual new progress forward.
1. Is this compliant to both Updating/Adding a Transport?
2. Is this compliant to both PSIP-Cable and PSIP-Terrestrial Types?
3. Is the data integrity of PSI/PSIP changes compliant enough to handle multiple instances of Transports w/ varying types?
4. Is the internal data handling of remaining Transports after deleting(+committing)a transport intact?


@pauljustinhernandez , Kindly continue your review on this.

**Comment by chriscodev** [comment]
hi @triveni-codev ,

apologies on this dancing PR,

    here are fix for this PR 

-     Is this compliant to both Updating/Adding a Transport?

        yes this is compliant  to both Updating/Adding a transport as well as Importing csv file

-     Is this compliant to both PSIP-Cable and PSIP-Terrestrial Types?

        Yes, this is compliant to both  PSIP Cable and Terrestrial

-     Is the data integrity of PSI/PSIP changes compliant enough to handle multiple instances of Transports w/ varying types?

        yes, both Importing and adding and Updating PSIP  cable  and  Terrestrial 
        but when  committing data on Cable it is not successfull as there is still an error on PSIP Cable


-     Is the internal data handling of remaining Transports after deleting(+committing)a transport intact?

    for channelEttPid when adding and updating, seems the return value is always zero, ive looked into swagger and the property is channelEttPid, and ive set all those value to be channelEttPid, it it still return zero

You may now verify in your end @pauljustinhernandez .

Cheers,
Christian

**Comment by pauljustinhernandez** [comment]
Hi Tian @chriscodev , sending here some concerns;
1. **Channel ETT PID** value became zero upon update
bug1T-Channel ETT PID value became zero upon update

2. bug encountered upon enabling and disabling PSI
bug2T-bug in enabling disabling PSI

**Comment by pauljustinhernandez** [comment]
Hi Tian @chriscodev , dropping here another concern;

1. bug encountered in enabling and disabling PSI upon BIG COMMIT. will send you the simulation clip via slack as the file is too big.

**Comment by chriscodev** [comment]
hi @pauljustinhernandez , 

I have new commit updates on this PR- you may now review on your end.


bug encountered in enabling and disabling PSI upon BIG COMMIT. will send you the simulation clip via slack as the file is too big. **updated**

Cheers,
Christian

**Comment by pauljustinhernandez** [comment]
Hi Tian @chriscodev , another bug appeared upon testing the big commit;

1. As a user I conducted a play-by-play testing for the BIG COMMIT, starting from importing a new transport to enabling and disabling the PSI. The issue was in the PSI settings, it seems like the app does not retrieve the static data for the PSI upon enabling it. See the clip below FYR.
bug4T-bug in PSI data upon commit

**Comment by chriscodev** [comment]
hi @pauljustinhernandez,

i have new commit  on this PR, you may now verify on your end, thanks :D

**Review by pauljustinhernandez — CHANGES_REQUESTED** [review]

**Comment by pauljustinhernandez** [comment]
Hi Tian @chriscodev , additional concern below

1. bug encountered again in enabling and disabling PSI upon BIG COMMIT. will send you the simulation clip via slack as the file is too big.

**Comment by chriscodev** [comment]
hi @pauljustinhernandez , 
i have new updates on this pr, fix bug concerns and removed console.logs, you may now verify on your end.

Cheers,
Christian

**Comment by pauljustinhernandez** [comment]
Another bug appear Tian @chriscodev ~ enable/disable logic of UPDATE PSIP button. Will send you the clip as file is too big.

**Comment by pauljustinhernandez** [comment]
LGTM Tian! @chriscodev , but please remove the console logs. Thanks!

cc: @triveni-codev

**Comment by triveni-codev** [comment]
This has been updated further w/ my additional review comments after Justin's remarks. Which includes concerning action items that I required from @chriscodev's long and concerning development track record of this.
Source: https://app.asana.com/0/1203486985240966/1203624253795183/f

**Pull request merged**
