### PR TITLE
chrisdev_bugHeader_1202522746056199

### PR DESCRIPTION
**Pull request by chriscodev**
ASANA Ticket : https://app.asana.com/0/1200833614787109/1202522746056199

[Bug] Dev Component toggler button defaults to checkbox when ran outside of local environment

### CODE REVIEW

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Things are just fine but I noticed once I toggled off, it will somewhat refresh the page and the toggle button seemed to bump. I might be wrong or no idea of the purpose but is it fine we comment out below condition for a smoother toggle on and off? If there's an underlying reason for that, is there a way to have a smoother toggle on and off?

image

**Comment by chriscodev** [comment]
hi @darlp5589 , 

new PR updates: https://github.com/triveni-codev/GBWebApp-dev/pull/444/commits/514a09d728e289dd2a3d2dea762acef13dcc89ca , this is a needed condition, so that when we access the dev sub content, and we toggle it off, it should not be dev component seen on the ui since it is toggled off.. it should be the default page which is dashboard.

Cheers,
Christian

**Review by darlp5589 — APPROVED** [review]
This is approved then.

**Comment by triveni-codev** [comment]
Commencing merge to master.

~~~~~~~~~~~
[Bug] Dev Component toggler button defaults to checkbox when ran outside of local environment
https://app.asana.com/0/1200833614787109/1202522746056199/f

**Pull request merged**
