### PR TITLE
Justin_Output-section-CRUD_1203077277702737_REVERTED

### PR DESCRIPTION
**Pull request by pauljustinhernandez**
ASANA ticket: https://app.asana.com/0/1203106518351809/1203077277702737/f

Description:
This is a rebuild ticket of https://github.com/triveni-codev/GBWebApp-dev/pull/476

### CODE REVIEW

**Comment by pauljustinhernandez** [comment]
Hi Darl, This is a rebuild ticket of https://github.com/triveni-codev/GBWebApp-dev/pull/476 as I need to rebase the branch from my last commit.
~ some of the issues were fixed in the last commit.

**READY FOR TESTING**
1. I have an existing output from server w/ linked transport, edited it then removed the linked transport and clicked update button. In the output list table, it's already marked as 0 under transport column but if you edit, it's still linking to the transport.
2. All issues you mentioned here https://github.com/triveni-codev/GBWebApp-dev/pull/476#pullrequestreview-1148399717

**TO DO**
1. Last Update column, there's no available data for this. need to discussed with the team

cc: @darlp5589

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking. I still have concerns on the fixes and I'll just screenshot here so you can see the actual concern number it points from the previous PR.

i1: from my latest concern from previous PR
i2: from my 2nd to the latest concern from previous PR

i1: 
image

i2: 
image

**Comment by pauljustinhernandez** [comment]
Hi Darl, some of the issues were fixed in the last commit.

**READY FOR TESTING**
1. issues raised here (from last comment) https://github.com/triveni-codev/GBWebApp-dev/pull/483#pullrequestreview-1150190064

**TO DO**
1. Last Update column, there's no available data for this. need to discussed with the team

cc: @darlp5589

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Checked and all previous fixes were fine. I just added a new one though you might consider fixing based on Java App. If you modify something on the outputs then eventually remove it, the big commit and revert button should be back to disabled mode. Example scenario from an existing output from server without a linked transport and you edit it to have a linked transport and save but you edit again and unlinked that transport then saved. The commit button should be back to disabled mode.

**Comment by triveni-codev** [comment]
PR #476 for review comments history/previous changes referencing is linked above. this comment

**Comment by pauljustinhernandez** [comment]
Hi @darlp5589 @triveni-codev , 

Re: https://github.com/triveni-codev/GBWebApp-dev/pull/483#pullrequestreview-1154638243

Hi guys, Unfortunately, I am having a trouble fixing this issue and I consumed a lot of time on this, since the initial codes are complicated to understand, and there are no components which were already implemented a fix for this (based on my investigation) to be mimic.

So, may I propose to create a separate ticket for this; be put in the backlog; and will be cherrypick if I have no primary tasks to do. This will help me to advance on my next tasks.

In addition, I think this issue is also included in the out-of-scope tasks for the CRUD-Output Section.

Let me know your feedback regarding this ASAP. Thank you.

**Comment by triveni-codev** [comment]
image

**Pull request merged**
