### PR TITLE
Justin_QI-Output-Section-Improvement_1203287929531935

### PR DESCRIPTION
**Pull request by pauljustinhernandez**
ASANA ticket: https://app.asana.com/0/1202364707885466/1203287929531935/f

Description: As a user I should be able to associate an uncommitted Transport within an Output

- created a function which will allow the user to associate an uncommitted Transport within an Output
- adjusted logics for tagging the Transport

cc: @triveni-codev

### CODE REVIEW

**Comment by pauljustinhernandez** [comment]
TO TEST:
- Add a new Transport (ATSC3) - just save and don't commit.
- Go to Output Section
- Add a new Output and associate a Transport
- ** As a user I should be able to associate an uncommitted Transport within an Output (should see on the list of Transport)
- Conduct a play-by-play scenario

Note: This is an initial development ~ the developer is aware that this has an out-of-scope issue 
**Ex. : After deletion of uncommitted Transport, App should also remove it in the Output.**
But will appreciate if the reviewer list down all the possible bugs. Cheers!

cc: @triveni-codev

**Comment by darlp5589** [comment]
Got this. Will do.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking PR. Here are my concerns:

1. i1: Create a new output then link to a newly/uncommitted transport, click prev and click next then click view. Now save it then click edit. Output type is gone. 
2. Same to above concern but this time, it's from an existing output being linked to a newly/uncommitted transport.
3. i2: Not sure if this is included in the scope but for the sake of listing down possible bugs, I'll just put this here as backlogs for future tickets. I have created output and linked to a newly/uncommitted transport then clicked big commit. An error popped out.
4. Still not sure if part of the ticket scope but I'll just put this as backlog here. Created an output and link to a newly created transport. Went to transport tab and renamed that newly created transport. Output linking that newly renamed transport is still holding the previous name though if you unlink and re-link it again, the options are now holding the updated name.
5. i3: Hexcode is gone after creating an output, linked to a newly/uncommitted transport then clicked prev and clicked next.
6. i3: I just noticed that the type value of a newly created (UNSAVED) output is different when it's already edited. Checking on java app, we should use "ATSC-3.0" (not ATSC_3) on both created / newly edited. 


i1: 
image

i2: 
image

i3: 
image

**Comment by pauljustinhernandez** [comment]
Hi Darl @darlp5589 , you can now check my fixes for the issues you've raised;

**READY FOR TESTING:**
- Create a new output then link to a newly/uncommitted transport, click prev and click next then click view. Now save it then click edit. Output type is gone.
- Same to above concern but this time, it's from an existing output being linked to a newly/uncommitted transport.
- Hexcode is gone after creating an output, linked to a newly/uncommitted transport then clicked prev and clicked next.
- I just noticed that the type value of a newly created (UNSAVED) output is different when it's already edited. Checking on java app, we should use "ATSC-3.0" (not ATSC_3) on both created / newly edited.


**TO DO / TBD:**
- Not sure if this is included in the scope but for the sake of listing down possible bugs, I'll just put this here as backlogs for future tickets. I have created output and linked to a newly/uncommitted transport then clicked big commit. An error popped out. 
- Still not sure if part of the ticket scope but I'll just put this as backlog here. Created an output and link to a newly created transport. Went to transport tab and renamed that newly created transport. Output linking that newly renamed transport is still holding the previous name though if you unlink and re-link it again, the options are now holding the updated name.

**Reference:** https://github.com/triveni-codev/GBWebApp-dev/pull/506#pullrequestreview-1183601591
**Note:** Hi Jan @triveni-codev, let me cc you on this as I think we need a separate discussion, and also I need your support regarding these two(2) items above.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking fixes. Here are my further concerns:

1. I just updated and linked an existing output (w/ or w/o linked transport) from server to a newly/uncommitted transport then clicked update. When I edited it, linking is gone.
2. i1: Can we have the TYPE value be ATSC-3.0 on all atsc3 type transport linking just for consistency purposes like in Java App? I noticed upon linking to an existing transport from server, it will use ATSC_3. 
3. I created an output then linked to a newly/uncommitted transport then saved. Edited it again then unlinked and linked to an existing/committed transport then clicked PREV, NEXT THEN CLOSE/CANCEL. Upon updating, it still link to the existing/committed transport even if it was cancelled already.
4. I have an existing output from server w/ linked transport, updated it and unlinked the transport then linked to a newly/uncommitted transport, clicked PREV, NEXT then CANCEL/CLOSE. Upon editing, it doesn't have anymore linked Transport. It should still be linking to the original linked transport.


i1: 
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking PR fixes on those items marked as "ready for testing".

I have 1 concern:

1. Upon checking the fix on ATSC_3 vs ATSC-3.0 value on TYPE field, I noticed it's fine if we have to link to an uncommitted/newly created transport but if we are to link on any existing transport from sever, there will be a series of switching values (from ATSC-3.0 to ATSC_3 then ATSC-3.0 again) upon clicking prev or saving it then click Edit. Though the last value is already correct.

**Review by darlp5589 — APPROVED** [review]
Done checking fixes. I have approved this. No further concerns!

LGTM!

**Comment by triveni-codev** [comment]
Confirmed + merged, after SVN repo rehabilitation got cleared

**Pull request merged**
