### PR TITLE
implemented auto unlink service-program if program gets deleted

### PR DESCRIPTION
**Pull request by darlp5589**
@triveni-codev , done implementing the remaining codes/conditions I previously implemented as preparation to auto unlink a service if its corresponding program gets deleted. Take note this is prepared already incase if the PR for delete program gets approved.

ASANA: https://app.asana.com/0/1201943683850147/1203308238794158

### CODE REVIEW

**Comment by triveni-codev** [comment]
Main reviewer for this will be assigned once Transport program deletion is approved and merged to master.

**Comment by triveni-codev** [comment]
I have merged the Transports Deletion PR (recently approved) to this PR so that it can be reviewed seamlessly as they are connected. This is now ready for review. This is a minor top-up of the base preparatory code as elaborated in the ticket and PR description.
Main reviewer: @pauljustinhernandez

**Comment by darlp5589** [comment]
Hi @chriscodev , as I checked on the concern, the repeated available transport for linking is only based on the global array from the set of transport which is GlobalVariables.transportsArray. So what happened there is every time we delete a transport either from server or uncommitted transport, that array still keep those deleted transport. Can you do me a favor to also remove those deleted transport in the global array so it won't affect all components that link it like the network channels and the outputs? Maybe place somewhere in deleteTableDataTransport(rowData) method of transport component on both conditions: // PURE DELETE (from server) and //ADD DELETE (uncommitted). To verify, you can put a console log at the end of that method and see how the GlobalVariables.transportsArray looks like.

**Review by chriscodev — APPROVED** [review]
LGTM

**Comment by triveni-codev** [comment]
Final checks have been sorted out. Commencing merge.

**Pull request merged**
