### PR TITLE
Justin_retrieve-LastUpdate-value_1202144121218545

### PR DESCRIPTION
**Pull request by pauljustinhernandez**
ASANA ticket: https://app.asana.com/0/1202144121218492/1202144121218545/f

Description: Retrieving the LastUpdate value via /outputStatus/{id} endpoint

### CODE REVIEW

**Comment by pauljustinhernandez** [comment]
**INITIAL DEVELOPMENT (for docu purposes):**

- Added OutputStatus endpoint in the service
- Created OutputStatus model
- Created a function which will trigger the OutputStatus endpoint via ENCODE OUTPUT button
- Created a function which will get the LastUpdate data in th endpoint response
- Created a function which will add and show the LastUpdate data in the Outputs list

**Comment by pauljustinhernandez** [comment]
**INITIAL DEVELOPMENT (for docu purposes):**
- https://github.com/triveni-codev/GBWebApp-dev/pull/511#issuecomment-1326474402
- Created a function which will simultaneously get the OutputStatus per id while looping inside the /getOutputs
- Created a function which will automatically add the **lastUpdateTime** key-value pair inside the Output object
- Created a function which will display the **lastUpdateTime** data in the Outputs data table

**Comment by pauljustinhernandez** [comment]
**INITIAL DEVELOPMENT (for docu purposes):**

- https://github.com/triveni-codev/GBWebApp-dev/pull/511#issuecomment-1327504841
- Finalized the encode functionality for the Output
- Created swal alerts

**Comment by darlp5589** [comment]
Got this. Checking.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking PR. Here are my concerns. I'm really not sure if I tested this right but I just based on the Testing specifications. You can enlighten me on a call tomorrow if necessary.

1. i1: I'm not sure if I tested this right but I still can't see the lastUpdate column having any value. out1 is from server which is already existing before I took this PR and out2 is newly created and it also has no lastUpdate column value on both dirty change and after big commit. In the Java App, both have lastUpdate column values.
2. i2: Clicking encode button on both Java App and Angular App, I still don't see any values from the lastUpdate column. I even got an error on the Angular App side.
3. i3: Checking on the networks tab on browser console, I can't see any /outputStatus/id being retrieved in the api call. Probably the reason why I don't have any of the lastUpdate columns values for all these records.


i1: 
image

i2: 
image

i3: 
image

**Comment by triveni-codev** [comment]
Main reviewer task substitute reminder to @chriscodev in the morning

**Comment by chriscodev** [comment]
hi @pauljustinhernandez ,

data are now updates i can now encode data, however i have a new concern:


qa1:
last Update Column, must be same with the App Date Time Format

qa2
on newly added data, encode and status button should be disabled

QA1
qa1

QA2
qa2

Cheers,
Christian

**Review by chriscodev — APPROVED** [review]

**Review by chriscodev — APPROVED** [review]
LGTM

**Comment by triveni-codev** [comment]
Merged. Final checks and Merge conflict mitigation had been carried out.

Side note(s): Due to the actual /encodeOutput API and stomp channel gap thats necessary to complete the whole encoding sequence, The java clientapp was used to perform the actual encoding operation (in testing of UI changes) before we could retrieve the latest update values for datetime in the angular webapp.

Full sequence to realize:
Network config notes - Page 1 Encode Output operation diagram

**Pull request merged**
