### PR TITLE
Darlp networks 1202626000178664

### PR DESCRIPTION
**Pull request by darlp5589**
Hi @chriscodev @pauljustinhernandez  @triveni-codev 

Kindly check this PR. 

ASANA Ticket here: https://app.asana.com/0/1202364707885489/1202626000178664

Please check specifically on handling dirty change for both adding and updating of one or more Network and Channel Descriptors per Descriptor Types.

Note: Big Commit isn't incorporated on this pushed commit yet. Will have a separate push commit for it after this.

Thanks!

### CODE REVIEW

**Comment by chriscodev** [comment]
hi @darlp5589 ,

Here are my review comments for this PR:

qa1: on click updated button opens a Add Network Modal , cant proceed on updating

qa2: on successfull adding atsc channel and clicking prev and click next the data is gone,
        on java app clicking prev and going next data is displayed

qa3: on adding atsc channel, when i clicked ok, it flashes a value on top says Edit ATSC Channel -{value}
    then table on atsc services is destroyed, it should not flash data being added and show destroy tabled

qa4: format on descriptor type is different and so is adding on table

qa5: when i tried updating descriptor type 2 or more times modal is changed on editing and descriptor adds new option selection

qa1
qa2
qa3
qa4
qa5

for now this are the concerns i have on the PR

Cheers,
Christian

**Comment by darlp5589** [comment]
[DONE] qa1: on click updated button opens a Add Network Modal , cant proceed on updating

[DONE] qa2: on successfull adding atsc channel and clicking prev and click next the data is gone,
on java app clicking prev and going next data is displayed

[DONE] qa3: on adding atsc channel, when i clicked ok, it flashes a value on top says Edit ATSC Channel -{value}
then table on atsc services is destroyed, it should not flash data being added and show destroy tabled

[DISREGARD UNTIL CSS CONCERN GETS FIXED] qa4: format on descriptor type is different and so is adding on table

[DONE] qa5: when i tried updating descriptor type 2 or more times modal is changed on editing and descriptor adds new option selection

**Comment by chriscodev** [comment]
hi @darlp5589 , 

Here are the new PR new comments for the new commit:

q1 - on adding new network, then updating newly added network does not display the newly added values

q2 - on edit 
    transport with server data on network descriptor,
    transport with server data on atsc channels then click updated then network descriptor
        try to click updated and edit the values and press cancel and 
        click again update button, the last inputted fields are  retained

q3 -  add placeholder for max value for both system id and PID in Conditional Access Descriptor

q4 - on edit
    transport with server data on network descriptor add descriptor tables then press cancel
    on edit it should not have the table cause i press cancel, it should be same on java app
    
    
q5 - on edit
     transport with server data on atsc channels then click updated then network descriptor with data
     try to edit the update then try to add channel descriptor then try to edit the newly added descriptor
     it opens the select descriptor with 5 types of descriptor

q1
q1


q2
q2


q3
q3


q4
q4


q5
q5


Cheers,
Christian

**Comment by chriscodev** [comment]
hi @darlp5589 ,

previous concerrn were solve, thanks,

there is a new concern i found, see attached image.

qa1
on server data click update then add  atsc service
    then commit it is successfull but when i click the newly updated data
       and atc service data is not found

qa2
    on adding new transport in client app i added 2 transport in psip-cable to match in network types
    and it displays data on linking transport but on the app on link transport it does not display available transport

=====================
qa1
qa1

qa2
qa2

**Comment by darlp5589** [comment]
Hi @triveni-codev , these 2 concerns were already good. I mean the 1st one isn't a concern related to this ticket's scope since it's about service. The 2nd one was recently created with a new ticket.

**Comment by triveni-codev** [comment]
Darl,

Thanks for rectifying me and putting ending closure on this.

**Pull request merged**
