### PR TITLE
chrisdev_transportService_1202372909367170

### PR DESCRIPTION
**Pull request by chriscodev**
Service Group handling continuation

- click edit - then add service group - [DONE]

- click edit - then add service group > add all settings > then update - [DONE]

- click edit - then add service group > add all settings then update then  click edit again > then add again - [DONE]

to follow add then edit service group - not started

Asana ticket: https://app.asana.com/0/1202364707885438/1202372909367170

### CODE REVIEW

**Comment by chriscodev** [comment]
Service Groups Continuation

-     click add input data atsc3 then add service groups

    add edit functionality

-     ongoing click add all service groups  

        then click update on newly added  atsc3

**Comment by chriscodev** [comment]
hi @triveni-codev :


new PR commit : https://github.com/triveni-codev/GBWebApp-dev/pull/436/commits/7691e3f287ac09e49d1128635fdc3c0dfdf002b4

just an update on this task

UPDATES on Commit: [chrisdev_transportService_1202372909367170 by chriscodev · Pull Request #436 · triveni-codev/GBWebApp-dev (github.com)](https://github.com/triveni-codev/GBWebApp-dev/pull/436/commits/7691e3f287ac09e49d1128635fdc3c0dfdf002b4)

- can now add-edit on first level modal only
- edit exitsting then add-edit on previous edit

- succeding modals on going
- 
ASANA TICKET: https://app.asana.com/0/1202364707885438/1202372909367170

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done with PR review. Here are my set of concerns:

Initially, we have Trans1 (atsc_psip_cable), Trans2 (atsc_psip_cable) and Trans3 (atsc_3) in the Transports Table List from the server. See image0.

image0:
image


1. image1 can be reproduced once I clicked Edit on Trans3 then added a service group and clicked update (it's fine on the 1st edit). Then clicked edit on Trans3 again and added another service group and clicked update. Seemed Trans2 gets overwritten.

2. image2 can be reproduced once I clicked on Edit on Trans3, changed transports name and clicked update then clicked edit on the newly edited Trans3 and changed the name again and clicked update.

3. image3 can be reproduced after adding new transport, inputted names, tsid and types den clicked add. Edit that newly added service group just the name only and clicked update (it's fine on the 1st edit). Now clicked that newly updated service group again and change still only the name and update. It overwrites the other transport record and will continue to overwrite if you keep on repeating the same process.

4. Another scenario of overwriting issue is when you clicked edit on a particular transport then don't change anything just click update and edit again that same transport, it will overwrite the other transport records even w/o changing any transport.

image1:
image

image2:
image

image3:
image

**Comment by chriscodev** [comment]
hi @darlp5589 ,

new fix for above issue: https://github.com/triveni-codev/GBWebApp-dev/pull/436/commits/a96364a90ddc9e91b4fbb33070b50233c914fd9b

can now add-edit on first level modal only

edit exitsting then add-edit on previous edit

succeding modals on going

ASANA TICKET: https://app.asana.com/0/1202364707885438/1202372909367170

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Here are my PR Review Comments:


1. image1 -> I was able to update an existing transport and added service group however when I attempted to update again that same transport, that shows up. I can't anymore add or edit a service group since Next Button is gone. Though it becomes fine once I closed that modal and update again that same transport.
2. image2 -> my newly added service group is gone after updating an existing transport.
3. image2 -> this also occurs for newly added transport with group service. It's gone when I attempted to edit that newly added transport.
4. image3 -> added a new transport (Trans4) then added another transport (Trans5) and edited that new transport (Trans5). The newly added and edited transport (Trans5a) overwrites the old one (Trans4). 

image1:
image

image2:
image

image3: 
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Here are my PR review concerns:

1. Previous concerns 1 and 2 still persist.
2. image1 -> Added new Transport and added a service group then clicked Add. Noticed that all values of service group is gone after I attempted to update that particular transport.
3. image2 -> tried attempting tsid of an existing transport but won't allow me to update. Client App allows it.


image1: 
image

image2: 
image

**Comment by chriscodev** [comment]
hi @darl,

fix concern on this commitL: https://github.com/triveni-codev/GBWebApp-dev/pull/436/commits/c57650449fd88681e53b71591e9c373def2fbf02


Previous concerns 1 and 2 still persist. - done
image1 -> Added new Transport and added a service group then clicked Add. Noticed that all values of service group is gone after I attempted to update that particular transport. - done
image2 -> tried attempting tsid of an existing transport but won't allow me to update. Client App allows it.
image1: - done

let me know darl if issue still persist.

Cheers,
Christian

**Review by darlp5589 — CHANGES_REQUESTED** [review]
All concerns were fixed except for below:

1. Added new Transport and added a service group then clicked Add. Noticed that all values of service group is gone after I attempted to update that particular transport.

-this is already good except  that the values of DSTP and Statmux are gone when attempted to update.

**Comment by chriscodev** [comment]
hi @darlp5589 , fix concern on PR 

you may now reivew on your end.
commit: https://github.com/triveni-codev/GBWebApp-dev/pull/436/commits/747eefdbb81fe47c6d1ee7d3e0bfb4eb4f2c68d6

Cheers,
Christian

**Review by darlp5589 — CHANGES_REQUESTED** [review]
All previous concerns were good. Just leave with a new one.

image

Kindly hide or disable that next button. It's currently clickable.

**Comment by chriscodev** [comment]
hi @darlp5589 ,

new update commit: https://github.com/triveni-codev/GBWebApp-dev/pull/436/commits/2dd677e6703364a20f02394e2870e94c293c7522

you may now review the commit updates thanks 🗡️

**Review by darlp5589 — APPROVED** [review]
Confirmed pending concern is fixed. 

I have approved this.

**Comment by chriscodev** [comment]
hi @darlp5589 , 
new commit: https://github.com/triveni-codev/GBWebApp-dev/pull/436/commits/5f9acda6e19036d36eb1b7027506fe922dc55b32

- this is for the new validation of vp1 embedders
- add vp1 embedders
- add edit data vp1 embedders
- edit data vp1 embedders

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Tested this along with GB client App. Here are my review comments:

1. image1: shouldn't green check if input is 0. Same case with Processing Instance and Server Code.
2. image2: port should only allow up to 5 digit inputs. Same case with Processing Instance (4 digist only) and Server Code (5 digits only).
3. image3: Epoch Year must only allow 4 digits and should be at least 2000.
4. Newly added VP1 embedder is nowhere to be found after clicking the Ok button thus can't proceed on checking edit feature.
5. Values for Edit Recovery Settings were cleared.


image1:
image

image2:
image


image3:
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Review Feedbacks:

1. image1: should green check 2000 and above value based on client app
2. image2: there's no way I can proceed on saving the vp1 embedder since epoch year wont allow any other values
3. putting values on edit recovery settings modal are not anymore cleared after  closing that modal, however, when I clicked OK button on Add Service Group modal, then clicked UPDATE on that service group, values for recovery settings are cleared.
4. image3: appears when I clicked update button on the newly added service group then clicked OK button. It pops up.

image1:
image

image2:
image

image3:
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done with PR review. Below are my comments:

1. image1: I was able to save vp1 embedders already however when I updated it with any value, it saves 2 records with the updated values.
2. I created a service group and clicked OK button then the modal closed. It's nowhere to be found.
3. image2: OK button in VP1 Embedders modal should be enabled as long as all these 4 fields have values. Any of these w/o a value will disable the OK button based on client app.

image1:
image

image2:
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Here are my feedbacks after checking this PR along with GB client app:

1. image1: This something optional though since the filters are working good. In the client app, for PORT field it automatically disables you to type any digits exceeding 65535 so when you type any values above it, it will only enable up to 4 digits. We have same implementation like this on IP Address, I believe we can use that concept. This also applies to  Processing Instance and Server Code. Again, you may disregard this suggestion since the filter being represented in the red checkmark will do. 
2. Still the newly created service group is nowhere to be found.
3. image2: Should have values on Host, Port, Processing Instance and Server Code before the OK Button gets enabled.

image1: 
image

image2:
image

**Comment by chriscodev** [comment]
hi @darlp5589 ,

new PR commit for review changes: https://github.com/triveni-codev/GBWebApp-dev/pull/436/commits/b9474a1eef1ab473428530fbad89a05a1aec047b

**Review by darlp5589 — APPROVED** [review]
All concerns are fine. This is approved!

**Comment by triveni-codev** [comment]
Acknowledged. Code design implementation and review comments handling have been carried out. Commenced merge checking of this PR deliverable into master. 

~~~~~~~
Where it all started: Service Group handling continuation
https://app.asana.com/0/1202364707885438/1202372909367170/f

**Pull request merged**
