### PR TITLE
chrisdev_v1embedDeletion

### PR DESCRIPTION
**Pull request by chriscodev**
Hi @triveni-codev ,

ASANA  TICKET: https://app.asana.com/0/1202364707885466/1203287929531879

VP1 Embedders DELTE FUNCTION

To  Test:
on server 
to be able to delete existing v1 embed  data
to be able to add and delete v1 embed data
to be able to cancel delete v1 embed data
to be able to commit and retrieve data

on newly added transport
to be able to add and delete v1 embed data
to be able to cancel delete v1 embed data

### CODE REVIEW

**Comment by darlp5589** [comment]
Got this.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Checked on PR. Here are my concerns: 

1. i1: Fix the Title and the message. That is the same VP1 record in both Java App and Client App.
2. v1: I have an existing set of VP1 Embedders from server and deleted all of them then clicked OK button on the Edit Recovery Settings Modal, when I clicked on CANCEL button of the Edit Service Group Modal, it should still be there but were already removed.
3. In relation to concern #2, same goes with adding vp1 embedder then clicked CANCEL button on Edit Service Group Modal, it will retain the newly added vp1 embedder when it shouldn't be.
4. In relation to concern #2, that concern will cascade to the Edit ATSC-3.0 Transport Stream Modal (the parent modal). So if you made adjustments to Edit Recovery Settings Modal and clicked OK then clicked OK also in the Edit Service Group Modal but clicked CANCEL on the Edit ATSC-3.0 Transport Stream Modal, that adjustment you did on the inner / child modals shouldn't reflect.

i1: 
image

v1: https://www.loom.com/share/19a219d469a54e4dacdb4d1adb5bc2a5

**Comment by chriscodev** [comment]
hi @darlp5589 , 

i have new PR updates on this commit: https://github.com/triveni-codev/GBWebApp-dev/pull/514/commits/eeb1cfc63fab9047cc288a4c825e4c0119df87ec

you may now verify in your end.

Cheers,
Christian

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking PR fixes. Here are my concerns:

1. v1: I have an existing transport with 2 group services (grp1 and grp2). I have updated grp1 and removed all existing vp1 embedders and added 1 vp1 embedder then clicked OK. Now, I have updated grp2 and merely adding 1 vp1 embedder on top of the existing ones then clicked OK. When I check on grp1 again, I realized all my changes did on grp2 reflected there. This is happening in vice versa. So basically, what ever group service is being updated last, it will reflect to the set of vp1 embedders on the other group service
2. In relation to concern #1, I also tried to do some updates on the vp1 embedders on the 2 group services then clicked UPDATE button on the Edit ATSC-3.0 Transport Stream Modal. When I checked again, grp1 is now holding the set of vp1 embedders on grp2.



v1: https://www.loom.com/share/ce9979e2655e4b80aa2a9298d95bbea7

**Comment by chriscodev** [comment]
hi @darlp5589 , i have new update  on my PR-you may now verify on your end, Thanks - https://github.com/triveni-codev/GBWebApp-dev/pull/514

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking PR fixes and confirmed they are good. I, however, noticed an odd behavior on the service group part that probably wasn't checked before during my testing. This isn't part of the ticket's scope though but can be a serious concern.

v1: I have 2 existing service groups (grp1 and grp2) from server, added 1 service group then renamed grp1 to grp1a then updated grp2 to grp2a. I noticed the update on grp2 will override grp1a and no trace of grp1a anymore.

v1: https://www.loom.com/share/c81b894ba9a94e079a43631ca47bcbcd

**Comment by chriscodev** [comment]
hi @darlp5589 , I have new updates on this PR, you  may now verify on your end.

Thanks,
Christian

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking PR fix. Previous concern is already fine but I noticed another bug scenario.

v1: I have a  transport from server with already 2 existing service groups (grp1 and grp2). I just clicked update button w/o doing anything then update again and added a new service group (grp3). As I try to add another service group and clicked close or cancel, there's an error that shows up about data table and it gets to create another instance of an empty service group in the service group list table.

v1: https://www.loom.com/share/c14ad5e3ff1d4e6ba4745215c28b5f49

**Comment by triveni-codev** [comment]
Additional review comment:
The stream of data for the depths of a Service group is affected after deleting a VP1 embedder on the following scenario:

Setup:
1. I want to make changes from an existing ATSC3 Transport (server-originating information). I now then modify that Transport by updating 2 unique service groups with unique VP1 embedders inside.


~~~
Something like this:
Service Group 1 has more than one VP1 embedders but one VP1 has to be dirty change.
Service Group 2 is completely "dirty" and has one one VP1 embedder
~~~~

2. Delete one VP1 embedder from Service Group 1.
Note: There should already be more than one VP1 embedders available in Service Group 1
3. Go back to the Service Group list table.
4. Select Service Group 2
3. Open Recovery Settings ->VP1 embedders list table

Expected Result:
Correct VP1 embedders list table should be displayed for Service Group 2

Actual Result:
Incorrect listing of VP1 embedders on the table. The data being funneled and displayed is for Service Group 1


~~~
My other concern is that, with so many regional if conditions being accumulated over time, this becomes hard to create a tight seal when fixing or changing just a single line of code. Kindly re-orient the big picture dynamics so that 
1. The dynamics/algorithm design could be made more self-correcting to minimize the "consequence of cat and mouse chase" after correcting or fixing a single bug or issue.
2. To confirm that a single state change on any scenario is being pulled correctly by all other scenarios that needs the latest state change.

**Comment by chriscodev** [comment]
hi @Darl @triveni-codev ,

I have new updates on this PR, and this is a regression fix, and both issues were fixed, 

Heres the diagram on the transport deletion and update diagram

Transport Deletion (1)


Cheers,
Christian

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking PR fix and the issue is already fine.

I have another concerns though which is specific for VP1 Embedders already.

1. v1: I have 2 existing service groups (grp1 and grp2). I added another service group (grp3) and clicked on Edit Recovery Settings button, a console error showed up.
2. v1: In continuation to above, not sure if this is an effect of the said issue but if you add a vp1 embedder, saved it and edit grp1's vp1 embedder, the changes did to grp1's vp1 embedder will reflect to the newly added grp3's vp1 embedders.

v1: https://www.loom.com/share/46a1564e6bb940098bcba6278a17bcb6

**Comment by chriscodev** [comment]
hi @darlp5589 , i have new update for the bug fix. you  may now verify in your end.

Thanks,
Christian

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking PR fix. I have another concern discovered. See below video link.

v1: I have 2 existing service groups (grp1 and grp2). I deleted vp1 embedders on both service groups. I then added another service group (grp3) and added vp1 embedder with 5555 value. I then clicked the entire transport modifications. When I clicked on update of the said transport and selected grp1, I noticed that the vp1 embedder (5555 value) of grp3 is reflected on grp1 vp1 embedder.

v1: https://www.loom.com/share/6606c09a26ec4043b9b6fff8e18f778c

**Comment by darlp5589** [comment]
Done checking PR fixes and the issue is already fine. My previous set of tests were on existing vp1 embedders. Now, I started testing with a newly created transport, new service groups and newly created vp1 embedder. I stumbled upon an error during creation process specifically on creating service groups for the 1st time. See vid below:


v1: https://www.loom.com/share/18609ce984cd45f8a1d09fa647a59734

**Comment by darlp5589** [comment]
Hi @chriscodev upon checking fix was good but when I update it again, I can't anymore see the vp1 embedder I added.

**Comment by chriscodev** [comment]
hi @darlp5589 ,i have new  updates on the vp1embbeder added, you may now verify on your end.

Cheers,
Christian

**Comment by darlp5589** [comment]
Done checking and previous concern was fixed. Another discovered concern below:

In continuation with previous fixed concern, the vp1 embedder is already there but when I added another vp1 embedder then eventually clicked CANCEL on 'Edit Service Group' modal, upon checking, the newly added vp1 embedder is still there even if CANCEL button is clicked.

**Comment by chriscodev** [comment]
hi @darlp5589 , i have new updates on this concern - https://github.com/triveni-codev/GBWebApp-dev/pull/514 you may now verify in your end, Thanks :D

**Comment by darlp5589** [comment]
Hi @chriscodev as I checked, the issue still persists. See this below vid:

https://www.loom.com/share/9c5d12838f2b46d4872398f95f1f3510

**Comment by darlp5589** [comment]
Done checking fixes and it was fine but upon clicking OK button (instead of CANCEL button) in 'Edit Service Group' modal after adding a new vp1 embedder, it should save it but it isn't.

**Comment by darlp5589** [comment]
Done checking PR fixes and was good already. I then noticed another scenario that needs fixing. See vid below:

https://www.loom.com/share/e619ddcc5aa14bbab0bd36fb907834f8

Created new transport, service group (grp5) and vp1 embedder then saved it. When I updated the grp5 and added new vp1 embedder but clicked CANCEL button, the existing vp1 embedder is gone along with the cancelled newly added vp1 embedder.

**Comment by darlp5589** [comment]
Hi @chriscodev done checking PR fix and was fine. I noticed this error not sure if from the fixed though.

link: https://www.loom.com/share/51a1b80061a84e9ca8c3123f6286583d

Added new transport and group service then vp1 embedder. As I opened the edit recovery settings button and clicked Cancel w/o doing anything, the vp1 embedder is gone.

**Comment by darlp5589** [comment]
Hi @chriscodev it's already fixed on 1 entry but on the next adding of vp1 embedder, it removes the other vp1 embedder on CANCEL. See here:

https://www.loom.com/share/89e0e7cfb1ae4c79b0657628d3b99ea0

**Comment by darlp5589** [comment]
Hi @chriscodev , per call and demo, I found this already fixed. Considered this PR approved then. Thanks!

**Review by darlp5589 — APPROVED** [review]

**Comment by triveni-codev** [comment]
Got this. Thank you @darlp5589 @chriscodev

**Pull request merged**
