### PR TITLE
Darlp networks 1203010547581779

### PR DESCRIPTION
**Pull request by darlp5589**
@chriscodev ,

Kindly check this PR bearing this ASANA Ticket: https://app.asana.com/0/1201943683850147/1203106518351860

Basically, you just need to test the max service logic in the serve license feature of the app.

If the Max Services is 5, it should only allow a total of 5 Services across all Channels across all Networks.

### CODE REVIEW

**Review by chriscodev — APPROVED** [review]
LGTM :D

**Comment by triveni-codev** [comment]
Darl,

Here is a carry-over check:

To apply on top, the explicitly identified code lines (review comments) that you decided at the time not to apply in https://github.com/triveni-codev/GBWebApp-dev/pull/462#issuecomment-1268263791.  Relating to strict type checking in comparison and optional chaining operator. Otherwise, the carryover from PR 462 is cleared.

**Comment by chriscodev** [comment]
Hi @darlp5589 ,

I've some review on the new commit

qa1 on server data existing link transport
	when i tried to unlink then link a transport select transport modal has a duplicate entry

qa2 i tried to add a new transport atsc-terrestrial and commit i have 3 transport
when i tried to add 3 atsc-terrestrial  in atscchannel in newly added network and commit it
transport is added anew duplicate transports is also added after commit

================

qa2
qa11

===========

video link
https://www.veed.io/view/8f6fb045-08c4-4f2d-b314-e558cc5cd21c/showcase?sharingWidget=true

**Comment by chriscodev** [comment]
hi @darlp5589  @triveni-codev,

ive attached here a new PR for the fix on the transport

https://github.com/triveni-codev/GBWebApp-dev/pull/477

on Darls PR LGTM :D 

Cheers,
Christian

**Pull request merged**
