### PR TITLE
chrisdev_transportDeletion_1203173080108786

### PR DESCRIPTION
**Pull request by chriscodev**
ASANA TICKET: https://app.asana.com/0/1203173080108752/1203173080108786

Transports Section Development: Transport Program Deletion functionality

1. To be able to delete one or more Transport Program, dirty change or not.
2. To be able to delete one or more Transport Program in multiple Transports, dirty change or not.

### CODE REVIEW

**Comment by darlp5589** [comment]
I will check on this.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking PR. Here are my set of concerns:

1. i1: Kindly make it consistent with Java App's delete confirmation box.
2. i2: I have 2 programs from server with numbers 1 and 2. I removed program 1 then added another program with number 2. Now I got 2 programs with number 2.
3. i3: I added a new transport then added 2 programs on it with numbers 1 and 2. I deleted the 2nd program with number 2 but the delete confirmation box says "delete program number 1" and it actually deletes program number 1.
4. i4: Not sure if this is related to concern #2 but I added a transport with program numbers 1 and 2 then removed program number 1 and clicked commit. When I updated that newly added transport, I can still add program number 2 thus I have 2 programs with numbers 2.
5. i5: I'm trying to merge from master but there are conflicts. Kindly check on them and let me know when to pull.




i1: 
image

i2: 
image

i3: 
image

i4: 
image

i5: 
image

**Comment by triveni-codev** [comment]
Hi @darlp5589 , I took the liberty to sort out the code conflict you encountered that hindered the successful compilation of the app. You can now continue with the Transport and Network synergy review process.

**Comment by darlp5589** [comment]
Copy. Will check.

**Comment by chriscodev** [comment]
hi @darlp5589 , updated this PR with the changes

i1: Kindly make it consistent with Java App's delete confirmation box. 
[DONE]

i2: I have 2 programs from server with numbers 1 and 2. I removed program 1 then added another program with number 2. Now I got 2 programs with number 2.
[DONE]

i3: I added a new transport then added 2 programs on it with numbers 1 and 2. I deleted the 2nd program with number 2 but the delete confirmation box says "delete program number 1" and it actually deletes program number 1.
[DONE]

i4: Not sure if this is related to concern https://github.com/triveni-codev/GBWebApp-dev/pull/2 but I added a transport with program numbers 1 and 2 then removed program number 1 and clicked commit. When I updated that newly added transport, I can still add program number 2 thus I have 2 programs with numbers 2.
[DONE]

i5: I'm trying to merge from master but there are conflicts. Kindly check on them and let me know when to pull. [UPDATED]

for this update, i have added the add delete functionality and made some fixes based on java app,

you may now verify this on your end.

=============================
ASANA TICKET: https://app.asana.com/0/1203173080108752/1203173080108786

Transports Section Development: Transport Program Deletion functionality

To be able to delete one or more Transport Program, dirty change or not.
To be able to delete one or more Transport Program in multiple Transports, dirty change or not.

Cheers,
Christian

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking PR fixes. See feedbacks:

1. i1: Should be Remove Program Confirmation in the Title
2. i2: In connection to previous concern #2, we may not be able to add 2 programs with same number 2 but please change that checkmark to red instead of green whenever we attempt to add another program with same number value.
3. Imagine this scenario: I have 2 programs from server. Program numbers 1 and 2. I removed program number 1. Now when I attempt to add program number 2, it's in green checkmark but the add button is disabled. So I have to change it to program number 3 then add. Now when I add another program, it will be number 3 in green checkmark but add button is disabled. So I have to change it to program number 4. The action cascades on the next set of values. Please fix the incrementation.
4. By the way, I just noticed this along the way while testing this PR. I tried to add a new transport (example trans6) then decided to add a program but eventually cancelled/closed adding the transport. Now, when I try to add another transport with trans6 name, it says it exists even though it was cancelled.




i1: 
image

i2: 
image

**Comment by chriscodev** [comment]
hi @darlp5589 ,

I have new update on this PR :

i1: Should be Remove Program Confirmation in the Title
{DONE}

i2: In connection to previous concern https://github.com/triveni-codev/GBWebApp-dev/pull/2, we may not be able to add 2 programs with same number 2 but please change that checkmark to red instead of green whenever we attempt to add another program with same number value.
{DONE}

Imagine this scenario: I have 2 programs from server. Program numbers 1 and 2. I removed program number 1. Now when I attempt to add program number 2, it's in green checkmark but the add button is disabled. So I have to change it to program number 3 then add. Now when I add another program, it will be number 3 in green checkmark but add button is disabled. So I have to change it to program number 4. The action cascades on the next set of values. Please fix the incrementation.
{DONE}

By the way, I just noticed this along the way while testing this PR. I tried to add a new transport (example trans6) then decided to add a program but eventually cancelled/closed adding the transport. Now, when I try to add another transport with trans6 name, it says it exists even though it was cancelled.
{DONE}

you may now verify on your end.

Cheers,
Christian

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking PR. Here are my concerns:

1. Attempting to add a transport then eventually cancelled it then add again a transport with same name -> it is now fine on the 1st attempt but on the 2nd try, it will display a message saying it exists if you cancel for the 2nd time.
2. I have an existing transport w/o a program from server. Updated it and added a program then saved. I have updated it again and deleted that added program. Commit/Revert button shouldn't be enabled.

**Comment by chriscodev** [comment]
hi @darlp5589 , new Fix update:

1.Attempting to add a transport then eventually cancelled it then add again a transport with same name -> it is now fine on the 1st attempt but on the 2nd try, it will display a message saying it exists if you cancel for the 2nd time.
[done]

2. I have an existing transport w/o a program from server. Updated it and added a program then saved. I have updated it again and deleted that added program. Commit/Revert button shouldn't be enabled. 
[this is out of scope , this is related to this PR - https://github.com/triveni-codev/GBWebApp-dev/pull/492]

Cheers,
Christian

**Review by darlp5589 — APPROVED** [review]
Upon checking. 1st concern is already good.

Since 2nd concern isn't part of this ticket scope, I have approved this!

**Comment by chriscodev** [comment]
hi @darlp5589, 

I have removed some of the console logs on this PR others are for reference.

https://github.com/triveni-codev/GBWebApp-dev/pull/489/commits/29e7af38eb67f2562ed43d8c2811c849609b2179

Cheers,
Christian

**Comment by triveni-codev** [comment]
Commencing merge as approved. Nice work.

**Pull request merged**
