### PR TITLE
chrisdev_transportSection_1202730791521673

### PR DESCRIPTION
**Pull request by chriscodev**
hi @darlp5589 , @triveni-codev ,

here are at the updates on this PR

[DONE] - i10: clientapp uses less than or equal symbol but not in the angular app

[DONE] -    i11: added mpeg-2 stream type then updated that by only appending pid value. That error shows up even if only 1 record and doesn't exist.

    same scenario, add an mpeg-2 then update and try to edit pid value then close/cancel, updating it again will retain the unsaved draft.

 [DONE] -   i12: had an existing mpeg2 stream type from server and clicked update button on it then closed. Now when I attempted to add a new elementary stream, it retained on the edit modal of that newly closed edit modal for mpeg2 record.
====================================================================
[DONE]    i1: first concern was already good but the moment I save any elementary stream then update it, I can proceed on updating without any PID value.

[DONE] i2: this was my previous 4th concern and it's still closing even on clicking outside modal.

 [DONE] -   i3: clicking cancel or close button can now go back to add program modal but clicking the prev button should go back to "add elementary stream modal".

 [DONE] - i4: any values on the add elementary stream modal will now be removed after clicking cancel but still retained when clicking the X button above.

[DONE] 5. language dropdown order is still different from clientapp (this was one of the mentioned fix but still persist)

Cheers,
Christian

### CODE REVIEW

**Comment by triveni-codev** [comment]
Tian, 

This is what we observed but only from our surface-level live demo observation.
The rest are confirmed with one connected observation below.

**Observation:**
The "Update" button inside "Edit Elementary Stream-MPEG2" modal is not enabled when a sequence of AC3-related actions beforehand is performed.

**To check and update the code sequence on the flow below:**


**Precondition:** Not necessary but you can an already existing Mpeg2 information from server

**Steps:**
1. Add new AC3 Audio
2. Afterwards Update that same AC3 Audio with different information. Ex: Update PID value to a different one
3. Click "Update" Button on an Elementary Stream row with Mpeg Type
4. Update PID value to a newer one

Expected result: Update button logic works normally -  enabled. Image attached.
image



Actual result: The detection for a mix of different Elementary Stream types does not detect that "Update" button must be enabled when there is a modification. Image attached.
image

**Comment by triveni-codev** [comment]
Tian @chriscodev ,

Review comments from recent code update:
1. Details in the image.
Network config notes - Page 1 PR 455 review

2. 
Starting Flow:
Edit existing Output -> Edit existing Program 

Steps:
1. Add a new AC3 Elem Stream and press OK
image
2. There are now 2(from 1) Number of elementary Streams which is correct.
image
3. However I select the "Update" button on that same Program....
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking all pending previous PR feedback fixes. Here are my further concerns:

1. i1: I can add 2 records of same PID but different stream types which isn't allowed in client app.
2. I have an existing AC-3 Audio Stream Type from server then I updated the value of the PID and clicked NEXT then clicked CANCEL on the next modal. Now click UPDATE on that AC-3 Audio record again will retain the value of the unsaved PID.
3. i2: I have an existing AC-3 Audio Stream Type from server and updated it on both Angular App and Client App. I noticed the Angular App isn't pulling the actual values from the server based on what is the Client App is being pulled. The image shows a side by side comparison of updating same record on the Angular app (left) and Client App (right).
4. i2: Also. it should say Edit AC3 Elementary Stream on the modal title upon updating AC3 Stream type.
5. i3: This is like a code that regressed but not sure coz when I added a program under "ADD PSIP TRANSPORT STREAM" modal then clicked OK w/o adding any elementary stream. Updating that newly added Program will show a modal w/o any title and all values are blank with a 0xNan codes.
6. i4: I added a new transport with a program and with an elementary stream then clicked ADD. Now when I update that newly added transport and proceed to the Program, I can't anymore find the elementary stream.
7. I have an existing elementary stream from server and updated just the PID then clicked UPDATE on that modal. It will now redirect to "Edit Program" Modal and clicked OK on it. It will now redirect to "Edit PSIP Transport Stream" Modal. Now click update on that program again. The updated values won't reflect.


i1: 
image

i2: 
image

i3: 
image

i4: 
image

**Comment by chriscodev** [comment]
hi @triveni-codev , review PR comments by jan is is this commit 

https://github.com/triveni-codev/GBWebApp-dev/pull/455/commits/4ae2f90b4a9d98379f21877eb1b64ce8ae8121c8

Cheers,
Christian

**Comment by chriscodev** [comment]
hi @darlp5589 , new commit updates; 

https://github.com/triveni-codev/GBWebApp-dev/pull/455/commits/883821399eb94ae597300441f7b583515076679a

DONE] - i1: I can add 2 records of same PID but different stream types which isn't allowed in client app.

[DONE] - I have an existing AC-3 Audio Stream Type from server then I updated the value of the PID and clicked NEXT then clicked CANCEL on the next modal. Now click UPDATE on that AC-3 Audio record again will retain the value of the unsaved PID.

[DONE] -  i2: I have an existing AC-3 Audio Stream Type from server and updated it on both Angular App and Client App. I noticed the Angular App isn't pulling the actual values from the server based on what is the Client App is being pulled. The image shows a side by side comparison of updating same record on the Angular app (left) and Client App (right).

[DONE] - i2: Also. it should say Edit AC3 Elementary Stream on the modal title upon updating AC3 Stream type.

[DONE] - i3: This is like a code that regressed but not sure coz when I added a program under "ADD PSIP TRANSPORT STREAM" modal then clicked OK w/o adding any elementary stream. Updating that newly added Program will show a modal w/o any title and all values are blank with a 0xNan codes.

[DONE] i4: I added a new transport with a program and with an elementary stream then clicked ADD. Now when I update that newly added transport and proceed to the Program, I can't anymore find the elementary stream.

[DONE]  I have an existing elementary stream from server and updated just the PID then clicked UPDATE on that modal. It will now redirect to "Edit Program" Modal and clicked OK on it. It will now redirect to "Edit PSIP Transport Stream" Modal. Now click update on that program again. The updated values won't reflect.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking fixes. Here are my further concerns:

1. i1: I added a record for mpeg2 stream type then added another record for ac3 audio with same pid of the mpeg2. The error message now shows up to avoid having same PID. However, when I change the value of the new record to any other number, the error message is still there.
2. i2: my previous 2nd concern was already fixed on the first attempt but if you do another attempt, the error persists.
3. i3: full service, language and channels were not pulled properly in the angular app thus inconsistent with the client app.
4. i4: this is about the concern I logged previously about a possible code regression and it seemed like the error persists probably due the the console error on the right. This is, by the way, from creating a new transport.
5. i5: adding a new transport with a program and with an elementary stream and save then updating that newly saved transport, we can now see the elementary stream. 
6. i6: my last concern previously is already fine but when I clicked on update on that particular elementary stream record, I can't proceed anymore probably due to error on the right.


i1: 
image

i2: 
image

i3: 
image

i4: 
image

i5: 
image

i6: 
image

**Comment by chriscodev** [comment]
hi @darlp5589 ,  new PR review updates,


[DONE] -  i1: I added a record for mpeg2 stream type then added another record for ac3 audio with same pid of the mpeg2. The error message now shows up to avoid having same PID. However, when I change the value of the new record to any other number, the error message is still there.


[DONE] i2: my previous 2nd concern was already fixed on the first attempt but if you do another attempt, the error persists.

[DONE] i3: full service, language and channels were not pulled properly in the angular app thus inconsistent with the client app.

[DONE] i4: this is about the concern I logged previously about a possible code regression and it seemed like the error persists probably due the the console error on the right. This is, by the way, from creating a new transport.

[DONE] i5: adding a new transport with a program and with an elementary stream and save then updating that newly saved transport, we can now see the elementary stream.

[DONE ]i6: my last concern previously is already fine but when I clicked on update on that particular elementary stream record, I can't proceed anymore probably due to error on the right.

Cheers,
Christian

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Here are my concerns:

1. i1: I still can same PID with a value of 0.
2. i1: add button shouldn't be enabled right away for ac3. It should proceed to the next modal first.
3. i2: Edit AC3 elementary stream modal shouldn't use an add button but an update button.
4. Add a new transport with a program even w/o elementary stream then click Add. Now update that newly added transport and CHANGE the Program NUMBER to any number and click OK on the "Add Program" Modal but click close/cancel on "Add PSIP Transport Stream" Modal. Now if you go back to update / check, it still saves the new NUMBER value even if it was cancelled.

i1:
image

i2: 
image

**Comment by chriscodev** [comment]
hi @arlp5589 ,

new Update fixes on this pr - https://github.com/triveni-codev/GBWebApp-dev/pull/455/commits/a934023e387cb28b0c0419e69ac44bae9a1a09ab

=======
[DONE] i1: I still can same PID with a value of 0.

[DONE] i1: add button shouldn't be enabled right away for ac3. It should proceed to the next modal first.

[DONE] i2: Edit AC3 elementary stream modal shouldn't use an add button but an update button.

[DONE] Add a new transport with a program even w/o elementary stream then click Add. Now update that newly added transport and CHANGE the Program NUMBER to any number and click OK on the "Add Program" Modal but click close/cancel on "Add PSIP Transport Stream" Modal. Now if you go back to update / check, it still saves the new NUMBER value even if it was cancelled.


Cheers,
Christian

**Comment by chriscodev** [comment]
HI @darlp5589 , new updates on this PR 


[DONE] i1: add button is still showing up for 'Add Elementary Stream' modal with AC3 Stream Type.

[DONE]  i2: can't proceed and got stuck probably due to the console error on the right.

[DONE]  i2: in relation to the error, I noticed some of the default field values were not preset anymore like the priority, sample rate, full service, etc.. I was merely adding a new transport with first and only one AC3 elementary stream.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Checked and here are my concerns:

1. i1: add button is still there. This happened when I created a new transport and first time to add new elementary stream with AC3 type (no existing elementary stream yet).
2. i2: can you confirm that big commit isn't implemented on this ticket yet? The one on the right is the actual value that I inputted for the big commit while the one on the left is the value after I clicked edit on that record from the server.
i1: 
image

i2: 
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Checked. Here are my further concerns:

1. i1: audio id and main service are 1 and 0 values respectively in the client app as default value for ac3 elementary stream form fields.
2. i2: data being retrieved after the big commit is still the same with the original data.


i1: 
image

i2: 
image

**Comment by chriscodev** [comment]
hi @darlp5589,

new updates and fixes: https://github.com/triveni-codev/GBWebApp-dev/pull/455/commits/d4ede1479db23fa330e714f8bd97473b2cf6eca8


[DONE] i1: audio id and main service are 1 and 0 values respectively in the client app as default value for ac3 elementary stream form fields.
[DONE] i2: data being retrieved after the big commit is still the same with the original data.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Here are my remaining concerns:

1. i1: after saving just the default value of AC3 modal fields, I tried updating but can't proceed because of the error on the console.
2. i2: based from the client app, every time we add an AC3 Elementary Stream, Audio ID and Main Service are increasing.
3. i3: added new transport with ac3 elementary stream -> clicked big commit -> retrieved the value of the newly added transport from server -> upon updating the associated ac3 elementary stream of the said new transport, I noticed a console error and also associated service got negative value, full service, bit rate, language and auto coding got no values being associated on them.

i1: 
image

i2: 
image

i3: 
image

**Comment by chriscodev** [comment]
hi @darlp5589 ,

new updates Commit:

[DONE] -  i1: after saving just the default value of AC3 modal fields, I tried updating but can't proceed because of the error on the console.

[DONE] -  i2: based from the client app, every time we add an AC3 Elementary Stream, Audio ID and Main Service are increasing.

[DONE] - i3: added new transport with ac3 elementary stream -> clicked big commit -> retrieved the value of the newly added transport from server -> upon updating the associated ac3 elementary stream of the said new transport, I noticed a console error and also associated service got negative value, full service, bit rate, language and auto coding got no values being associated on them.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Here are my concerns:

1. i1: default value auto selects the Channels radio button instead of the Audio Coding from Client App.
2. i1: I just manually set to Audio coding instead of Channels and the rest are just the default values then clicked ADD. When I updated that AC3 record, it auto selects the Channels again.
3. i2: The updates after the big commit were already good. Updating with dirty change on those data from the server after a big commit is also good. However, after doing some updates on the data from server then clicked big commit again, that shows up.

i1: 
image
 
i2: 
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Fixes are confirmed fine already. Below are another concerns:

1. I just noticed that we can add same values of audio id and main service on different AC3 elementary stream. It should be unique. Which means if you have used value of 2 for audio and value of 1 for main service, you can't use those values for other AC3's audio id and main service respectively.
2. i1: I have added two AC3 elementary stream types with PIDs 2 and 3. When I tried to update the AC3 with PID of 3, I am redirected to the other AC3 with PID = 2 modal. I don't have any way to update AC3 with PID = 3.

i1: 
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Pending concerns:

1. I still can proceed on having same Audio ID or Main Service values across different AC3 Elementary Stream types.
2. I still encountered the 2nd concern. So I added three AC3 Elementary Stream types and every time I attempt to update any of the three, it will always be the 1st record being shown. Take note the "Edit Elementary Stream" modal appeared to be fine on those 3 but the "Edit AC3 Elementary Stream" modal part only displays same for all which is the first AC3 record.

**Comment by chriscodev** [comment]
hi @darlp5589 ,

new updates Commit::

[DONE] I still can proceed on having same Audio ID or Main Service values across different AC3 Elementary Stream types.

{DONE} I still encountered the 2nd concern. So I added three AC3 Elementary Stream types and every time I attempt to update any of the three, it will always be the 1st record being shown. Take note the "Edit Elementary Stream" modal appeared to be fine on those 3 but the "Edit AC3 Elementary Stream" modal part only displays same for all which is the first AC3 record.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking fixes. Here's another pending concern probably a branching from the fixes 

1. i1: I added 2 AC3 Elementary Streams with values below. When I try to update the 2nd one with same value of 3 and 1 for audio id and main service respectively, the red checkmark shows up and it won't anymore turn back to green even if I change it to other unused values like 4 and 5 audio id and main service respectively.
   -audio id: 2, main service: 2
   -audio id: 3, main service: 1
2. In connection to concern above, simply updating any AC3 value for audio id and main service to an unused value would trigger to show up the red checkmark.
3. Just a suggestion to use red X mark instead of red checkmark to be consistent with client app.


i1: 
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Here are my recent concerns on the fix:

1. main service logic filtering a repeating value seemed not working anymore.
2. i1: assuming value for audio id is 2 on my first AC3 record, in the 2nd AC3 record, upon inputting a value of 2, it will force my input to be 1 with a red checkmark.



i1: 
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Here are my recent concern on the fix:

1. main service logic filtering a repeating value still didn't work. 1st AC3 audio id: 2 and main service: 2 then 2nd AC3 can have a value of audio id:3 and main service: 2.
2. did the same scenario with my 2nd concern and it still force a change on my input to 0 instead of 1 with a red checkmark.

**Comment by triveni-codev** [comment]
Hi @chriscodev,

The Comprehensive elementary Streams development ticket is not yet done especially in the AC3 AudioId and Main Service Value's specialized algorithm implementation as thorougly inspected during PR review.


Given that:
1) This task has taken some time to get accomplished (AUdioId/MainService portion) and that this PR seems to be chasing the tail everytime aka Fixing a logical portion opens up another Issues.
I'm gonna need you Tian to properly compartmentalize and rethink this one in a methodical technical engineer manner once we get to hear from Sean regarding the odd pattern observed in the clientApp itself
2) and that there will be an awaiting confirmation on Sean's end,

We have discussed that we will close and merge this PR but the review comments will still continue and link the issues found here in another ticket.


~~~~~
Comprehensive Elementary Streams refinement from review comments and from designed base code foundation
https://app.asana.com/0/1202657659482238/1202730791521673/f

**Pull request merged**
