### PR TITLE
chrisdev_bugTransportCommit_1203318703397642

### PR DESCRIPTION
**Pull request by chriscodev**
ASANA Ticket: https://app.asana.com/0/1203287929531882/1203318703397642

Scenario fixing on Multiple Transports regardless of its type being committed at once

source of bug is in here:
https://github.com/triveni-codev/GBWebApp-dev/pull/492#issuecomment-1305976313

Cheers,
Christian

### CODE REVIEW

**Comment by triveni-codev** [comment]
Tian @chriscodev , before I assign this to main reviewer. Kindly remove the newly pushed console log fragments that were testing-related and not necessary to be included to master. Thanks.

**Comment by chriscodev** [comment]
hi @triveni-codev , new updates on this PR

removed console.logs on this commit:
https://github.com/triveni-codev/GBWebApp-dev/pull/495/commits/a3bc055e9c3d6327d66522eb2a17f56967fed749

Cheers,
Christian

**Comment by triveni-codev** [comment]
Above clean-ups confirmed. Cheers. Admitted for main review once folder name revamp is carried out. This PR might be corrupted if it is updated in parallel (A Github-related concern)

**Comment by pauljustinhernandez** [comment]
Hi Tian, new PR concern here;

- Commit and revert btns, doesn't go back to disable mode after reverting the changes. 
Note: in the clip below, I only simulated the transport name but the bug also applies on the other data fields.
bug

cc: @chriscodev

**Comment by chriscodev** [comment]
Hi @pauljustinhernandez ,

You may now test this new Commit :https://github.com/triveni-codev/GBWebApp-dev/pull/495/commits/f05b08adb8bed4da9bc1aae50842b5a972894631

this is a fix for your findings

Cheers,
Christian

**Comment by pauljustinhernandez** [comment]
Hi Tian, new PR concerns here;

1. Commit and revert btns, doesn't go back to disable mode after reverting the changes (for other fields). 
bug1
bug2
bug5

2. Same concern with number 1, but the other issue here is that the app doesn't detect my changes when I edit the PSIP table setting.
bug3

3. Issue between AngularApp and CilentApp Re: **Number** data field in the program
bug4-number field in program

4. **Update** btn should be disable if there are no changes in the data yet
updatebtn_disabling

cc: @chriscodev

**Comment by pauljustinhernandez** [comment]
> 

1. kinda FAILED (will list additional bugs on my next comment which correlates to this issue)
2. OK copy that!
3. Issue encountered again, please counter check on the clientApp.
4. I thought this an additional feature of the app to minimize some issues on the edit mode. Nevertheless, it's confirmed that the Update btn is enabled in the clientApp.

cc: @chriscodev

**Comment by pauljustinhernandez** [comment]
Dropping some additional concerns here;

1. Undefined error when updating a Transport - ATSC3 type (can't proceed)
bug6-undefined error

2. Disabling bug of OK button in the Program section
bug7-edit program OK btn

3. the app doesn't detect my changes when after adding a program
bug7-program not added

**Other issues to re-check**
- Issue between AngularApp and CilentApp Re: Number data field in the program

cc: @chriscodev

**Comment by chriscodev** [comment]
hi @pauljustinhernandez ,

I have updates on this branch:
https://github.com/triveni-codev/GBWebApp-dev/pull/495/commits/3958efe9c97b1a0a271db1d7e32beaadcfc5d0bb

1. Undefined error when updating a Transport - ATSC3 type (can't proceed) [updated]
2. Disabling bug of OK button in the Program section [cant replicate]
3. the app doesn't detect my changes when after adding a program [cant replicate]
4. Issue between AngularApp and CilentApp Re: Number data field in the program[update]

you may now verify in your end.

**Comment by pauljustinhernandez** [comment]
Hi Tian @chriscodev , below are my new PR concerns;

**Re:** https://github.com/triveni-codev/GBWebApp-dev/pull/495#issuecomment-1319476710
- Undefined error when updating a Transport - ATSC3 type (can't proceed) **PASSED**

- Disabling bug of OK button in the Program section ~ I didn't notice in the clip that I have created Tian that the program number is invalid (has a red check) I think that's the reason why OK btn is disabled. Nevertheless Tian, upon counter-checking the clientApp, it should not be disabled when the user edits the **PCR PID** .  Please refer to the clip below;
bug7-edit program OK btn

- the app doesn't detect my changes when after adding a program ~ Issue encountered again, Please re-check the clip on my previous comments regarding this. We can also have a quick call for me to be able to simulate it to you.

- Issue between AngularApp and CilentApp Re: Number data field in the program ~ Issue encountered again, Please re-check the clip on my previous comments regarding this. We can also have a quick call for me to be able to simulate it to you.


**ADDITIONAL BUGS:**

- Undefined error when updating service group name - ATSC3 type
bug8-undefined servicegrp name

- Multiple bugs encountered when adding a service group
bug10-multiple bugs adding a service grp

- Multiple bugs encountered in LLS groupID
bug9-multiple bugs LLS grpID

**Comment by chriscodev** [comment]
Hi @pauljustinhernandez ,

New update on the branch, made some changes on atsc3 transport, it took me a while to restructure the service group and atsc parent child  communication, and lls is now working, some codes where  removed and some have some issue, but anyways, this is  now ready for your review.

Cheers,
Christian

**Comment by pauljustinhernandez** [comment]
Hi Tian @chriscodev , below are my new PR concerns;

**Re:** https://github.com/triveni-codev/GBWebApp-dev/pull/495#issuecomment-1319632234

- Disabling bug of OK button in the Program section ~ Cause by Program number validation field.
bug11-program number validation

- the app doesn't detect my changes when after adding a program. **PASSED** ~ 
but there's a bug upon updating the newly added program (undefined error)
bug12 -edit program undefined error

- Issue between AngularApp and CilentApp Re: Number data field in the program ~ Upon updating my GBOne to latest, the issue still exist. But as you mentioned during our discussion earlier, this bug is in the ClientApp and not on AngularApp. To close this issue, just please confirm and acknowledge this Tian. Thank you. Also, I'll cc you here Jan @triveni-codev Re:  ClientApp bug. See #3 here https://github.com/triveni-codev/GBWebApp-dev/pull/495#issuecomment-1316380052 FYR.

- Undefined error when updating service group after adding a new one - ATSC3 type
bug13 -Undefined error when updating service group

**Comment by chriscodev** [comment]
hi @pauljustinhernandez ,

I have new update on this PR, hope  fully this will be approved:

1. Disabling bug of OK button in the Program section ~ Cause by Program number validation field. **[done]**
2. but there's a bug upon updating the newly added program (undefined error) **[done]**
3. Issue between AngularApp and CilentApp Re: Number data field in the program **[done]**
4. Undefined error when updating service group after adding a new one - ATSC3 type**[done]**

you may now verify on your end.

Cheers,
Christian

**Comment by pauljustinhernandez** [comment]
Hi Tian @chriscodev , below are my new PR concerns;

1. Program number field should not allow zero and null value
bug14 - program number - zero value is not allowed
bug15 - program number - null value is not allowed

**Comment by chriscodev** [comment]
hi @pauljustinhernandez ,

youmay now check this new commit:

https://github.com/triveni-codev/GBWebApp-dev/pull/495/commits/09b6b20992df30fb6ecd33b0e29e37ed96862689

1. Program number field should not allow zero and null value [done]


Cheers,
Christian

**Comment by chriscodev** [comment]
Hi @pauljustinhernandez ,


you may now review  my update: https://github.com/triveni-codev/GBWebApp-dev/pull/495/commits/8b63578d6dd91857487e3ec996c170bcb9b93d7d

updates added a pattern on input Numbers that will only accept positive numbers

and  added a directive folder to stop from copy pasting data from their fields

and remove unnecessary consoles

cheers,
Christian

**Comment by pauljustinhernandez** [comment]
Hi Tian @chriscodev , below are my new PR concern;

- Elem stream PID field - should not allow negative,string, and copy paste value
bug17 - Elem stream PID field - should not allow negative,string, and copy paste value

- bug in elementary stream data retrieving
bug18 - bug in elementary stream data

- You can add **autocomplete="off"** in the input tag to block auto suggestion  (Please apply the fix on all number fields within the Transport Section if necessary)
b

**Comment by chriscodev** [comment]
hi @pauljustinhernandez ,

new updates on my commit:https://github.com/triveni-codev/GBWebApp-dev/pull/495/commits/320e5d2f5eeffd7e0ffd18be3277d54a252bbe85

- Elem stream PID field - should not allow negative,string, and copy paste value [ updated]
- bug in elementary stream data retrieving [updated]
- You can add autocomplete="off" in the input tag to block auto suggestion (Please apply the fix on all number fields within the Transport Section if necessary) [updated]
- 
Cheers,
Christian

**Comment by pauljustinhernandez** [comment]
Hi Tian @chriscodev , below are my new PR concern;

- Elem stream PID field - implement autocomplete off
- Bug in elementary stream OK btn
bug19 - bug in elementary stream OK btn

- remove console logs

**Comment by chriscodev** [comment]
hi @pauljustinhernandez ,

new updates on my commit: https://github.com/triveni-codev/GBWebApp-dev/pull/495/commits/dd0887a361b6ad520cb9aaacb3ff412b9be4617b


Elem stream PID field - implement autocomplete off [updated]

Bug in elementary stream OK btn [updated]

remove console logs[updated]

Cheers,
Christian

**Comment by pauljustinhernandez** [comment]
LGTM Tian @chriscodev ! Cheers!

**Comment by triveni-codev** [comment]
Confirmed + merged, after SVN repo rehabilitation is cleared

**Pull request merged**
