### PR TITLE
Justin_BUG-Flagging-irregularity-after-linking-a-transport_1203349862726082

### PR DESCRIPTION
**Pull request by pauljustinhernandez**
ASANA ticket: https://app.asana.com/0/1200833614787109/1203349862726082/f

Description: Fixed the flagging irregularity after linking a Transport in an Output

### CODE REVIEW

**Comment by darlp5589** [comment]
Will check.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking. My main concern is fixed already but I have another concern from the fix:

i1: Add an output, link to a transport, click prev, click next, click view and ok button then click prev and lastly click next. It becomes empty.
i2: Add an output with a linked transport and click add button. Edit that output and remove the transport but click prev. If you click next, it still saves the supposedly removed transport.
i3: Add an output w/o a linked transport. Then edit that output and link a transport then unlink. Now link to a transport again then click prev. When you click next and view, a console error shows up.


i1: 
image

i2: 
image

i3: 
image

**Comment by pauljustinhernandez** [comment]
Hi Darl @darlp5589 , fixed PR concerns Re: Flagging irregularity after clicking the next and prev btns recurringly.

**READY FOR TESTING**
- Add an output, link to a transport, click prev, click next, click view and ok button then click prev and lastly click next. It becomes empty.
- Add an output with a linked transport and click add button. Edit that output and remove the transport but click prev. If you click next, it still saves the supposedly removed transport.
- Add an output w/o a linked transport. Then edit that output and link a transport then unlink. Now link to a transport again then click prev. When you click next and view, a console error shows up.

**Review by darlp5589 — APPROVED** [review]
Done checking. All fixes were good. I have approved this.

**Comment by triveni-codev** [comment]
Merged as approved. Final checks were performed.

**Pull request merged**
