### PR TITLE
chrisdev_transportSction_1202967506693172

### PR DESCRIPTION
**Pull request by chriscodev**
- Transports Section Development: AudioId development update
ASANA TICKET: https://app.asana.com/0/1202929493355635/1202967506693172

In response to [[Inquiry] AC3 Elementary Stream - AudioId's observed offbeat pattern](https://app.asana.com/0/1200833614787143/1202879856899828/f), this will be the new objectives:

### CODE REVIEW

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking Audio ID feature changes. Here are my concerns:

1. I just discovered this along the way while testing audio ID, I just logged it here to be sure coz Main Service still not trapping repeating response. Example value for audio id and main service are both 2 on first record then 2nd record, adding value of 2 on both audio id and main service will trap but if you change the value of audio id to 1, main service will turn to green check.
2. i1: After already using the value of 1-7 for Audio ID, shouldn't we default it back to zero to allow adding more?
3. i2: After already using the value of 0-7 for Audio ID, I think we shouldn't allow adding more AC3 Elementary Stream based on the ticket requirement. 


i1: 
image

i2: 
image

**Comment by chriscodev** [comment]
hi @darlp5589 , new PR updates

DONE: I just discovered this along the way while testing audio ID, I just logged it here to be sure coz Main Service still not trapping repeating response. Example value for audio id and main service are both 2 on first record then 2nd record, adding value of 2 on both audio id and main service will trap but if you change the value of audio id to 1, main service will turn to green check.

DONE:  i1: After already using the value of 1-7 for Audio ID, shouldn't we default it back to zero to allow adding more?

DONE:  i2: After already using the value of 0-7 for Audio ID, I think we shouldn't allow adding more AC3 Elementary Stream based on the ticket requirement.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking. Here's my lone concern:

Can we just not let this scenario happen wherein a user tries to add an AC3 Elementary Stream with a disabled audio id and main service (because they are all used up) only to find out they still can't proceed anyway, instead, just maybe take out AC3 from the Dropdown Box of the ADD Elementary Stream Modal?

image

**Comment by chriscodev** [comment]
hi @darlp5589 , Pr has been updated, you may now verify on your end.

Cheers,
Christian

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking my lone concern but I noticed another concern after the fix. See below.

1. i1: I created a new transport, added a program then attempted to add an elementary stream for the firs time. It says Edit in the Modal Title and in fact if you fill in all the required fields, it will activate the update button. Also I can't proceed on the fix since I can't change the Stream Type coz it's disabled.

i1: 
image

**Comment by triveni-codev** [comment]
Additional discoveries found on top of Darl's.

Observations:
1. Gonna need full bullet points/thought process of the code changes because "new commits" alone does not provide a better view of the multiple changes.
image
2. Every push commit seems to shift the spacing from tabs to space and then sometimes from space to tabs and so on. This creates unnecessary change and resistance if a PR is going through multiple commits.

Review:
1.  The Max elementary streams must not be statically limited to 8.  Should be dependent on whether the audioId limit (can be up to 256) has been reached. The statement where Sean mentioned that "more than 8 AC3 is not allowed" was just an old example.
2. The line comment does not describe the purpose of the if{} loop accurately. Also, this would be better placed inside a function since this performs an explicit single task~ to check if the AC3 limit has been reached and whether to remove the AC3 dropdown or to disable it.
image


We can just discuss these in the call.


@chriscodev

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking fix. Here's my new concern on the fix did:

i1: After using all the available Audio Id, it already removed from the dropdown but updating any of those AC3 record, you can't find the AC3 already as the default value in the disabled dropdown.

v1: After using all the available audio id, I tried updating any of the AC3 records and noticed the green checkmark on the side will still appear with a console on the right. See the vid.


i1: image

v1: https://www.loom.com/share/41da16f47e984602a5b0acff121f7472

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Checked and my 2nd concern is still there.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Checked and here is my concern:

i1: I encountered a console error right away even on my 1st adding of AC3 Elementary Stream. It also displayed in red checkmark but can proceed on adding though.

i1: 
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Checked and here are my other concerns probably from the fix made:

i1: I already used all the 8 audio id, updated the record with audio id=5 to 1 then clicked prev and clicked next. The checkmark is already in red which is already correct but the update button below is enabled already which can proceed.
i2: I have added an AC3 record with audio id=1. Now I attempt to create another AC3 record with audio id=0 by default but I tried to change it to 1 (which was already existing) and the checkmark is already in red which is correct. Now I click PREV then click NEXT, the audio id is now revert to 0 which is also correct but the checkmark is still in red which is supposed to be in green.

i1: 
image

i2: 
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking. Another concerns:

v1: Noticed that main service was also changed from 2 to 0 with a green checkmark. I have already an existing AC3 with main service=0.
v2: After using all the 8 audio id values and updating any of the AC3 records, I can now edit to any used audio id values already and can even type 8 and 9.


v1: https://www.loom.com/share/e6431542c2164ae3814e6e4526a96b15
v2: https://www.loom.com/share/efffa6bf8601416984d96143a217fd39

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking. The 1st concern is already good. The 2nd one is still there.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking. All fixes were already good however I found another issue that could cause another inconsistency of the audio id logic after comparing with client app.

v1: in the video below, you may notice that all audio id were already used. Now I'm going to update the record with audio id=6 to 7 which is also existing. As you notice, the checkmark is already in red which is correct but if you click PREV button then click UPDATE, it will update to 7 and that will cause the issue since there's already an existing AC3 with audio id = 7.

v1: https://www.loom.com/share/6d1589d610eb4be0b9a04dcdc7f27ca9

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking. Noticed the error fix worked but another concern appeared.

v1: Used all the audio id and edited one of the record bearing audio id = 1 to 7. The check mark is already in red but the update button is activated and can be updated. Now I have 2 records bearing audio id=7.

v1: https://www.loom.com/share/72149e5de5d04502ab37f58cbeba65b3

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Concerns here:

v1: I added just 2 AC3 records with 2 and 3 PID values but when I attempted to update the record with PID=2 to any used PID values, it will show an error message which is correct but I can't anymore retain the value of 2 and proceed on NEXT button.
v2: In connection to v1, after updating the value of PID=2 to 4 but clicked cancel then added another record of AC3 with a value of PID=4, that will happen. It will now have 2 records with PID=4.
v3: The recent fix was working but noticed as I changed the value of audio id=2 to any number that was used, the check mark turns red which is correct but when I clicked on PREV button and proceed on NEXT, it will automatically change to aidio=2 whioch is correct but still in red check mark and with disabled UPDATE button. Even if I try to change anything like the description, the UPDATE button is still disabled. It will only be enabled once I change the audio id of 2 to the same value of 2.


v1: https://www.loom.com/share/217dae97ef1a4026bc67f20c999c4db8
v2: https://www.loom.com/share/ca380f214ab94919829ae5c2208c3a8f
v3: https://www.loom.com/share/101f4f8b0c6945e1afeeae9da98ac3b3

**Comment by triveni-codev** [comment]
Hi @chriscodev, it has become a concerning cat and mouse chase everytime a fix is added (not optimal ins and outs tracking). For escalation and so we can put the chase to rest easier, requesting to create this time, a detailed birds eye view algorithm flowchart of the audioId logic from A to Z entrapping the dirty change that started from the, 
a) server-returned info +
b) a completely new info to commit that has no link from the server yet.  

I also don't get enough "explanation of the fix" details from the commits made. Hard to explain to Dave the thought process without me having to deeply examine further what was technically considered  in the fix commit.

**Comment by triveni-codev** [comment]
I created an example flowchart so that everyone gets to see the big picture example of what to expect.

Use the screenshot as a base reference only (as it is not perfect)  for adding and updating use cases.

Things like this could be used as a reference during review to check if a certain functionality was considered during coding.


Mind map - Page 1 AudioId logic trapping flowchart

**Comment by triveni-codev** [comment]
Log(s): 
Had further flowcharting discussion w/ Tian to help me understand better on complexities that I missed. 
One may Ignore the previously created flowchart above as it is now incomplete and deprecated. 

Moving on, continuous updates of flowchart including the "Update" use case flowchart is implemented by Tian.

~~~~~
 Regardless of whether the development is going well or not, the goal of this flowcharting here is still 1) to better get a full map of the sequences and 2) detect possible trapping and leaks in the coding/"review comment updates" phase.


Use cases:
a) AudioId logic dynamics during "Add" use case
b) AudioId logic dynamics during "Update" use case

Cheers

**Comment by chriscodev** [comment]
Hi @darlp5589 ,

new PR fix: https://github.com/triveni-codev/GBWebApp-dev/pull/468/commits/dc6f985f9b8bb4341c0f634ddcdc46c517276d2b

v1: I added just 2 AC3 records with 2 and 3 PID values but when I attempted to update the record with PID=2 to any used PID values, it will show an error message which is correct but I can't anymore retain the value of 2 and proceed on NEXT button.
**- updated condition to mark original [DONE]**

v2: In connection to v1, after updating the value of PID=2 to 4 but clicked cancel then added another record of AC3 with a value of PID=4, that will happen. It will now have 2 records with PID=4.
**- update the cancel to retain the value of original data [DONE]**


v3: The recent fix was working but noticed as I changed the value of audio id=2 to any number that was used, the check mark turns red which is correct but when I clicked on PREV button and proceed on NEXT, it will automatically change to aidio=2 whioch is correct but still in red check mark and with disabled UPDATE button. Even if I try to change anything like the description, the UPDATE button is still disabled. It will only be enabled once I change the audio id of 2 to the same value of 2.
**- updated data JSON.parse(JSON.stringify) to capture the previous data and store in the Next form [DONE]**

Cheers,
Christian

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking. Here are my concerns:

v1: I can see that the first concern I raised was fixed but when I proceed to update the audio id from 2 to 4, I am not allowed as the update button is disabled.
v2: My previous 2nd concern still persist. Updating existing AC3 with PID=2 to 4 but cancelled it then added another AC3 with PID=4, it will messed up the Elementary Stream list.
v3: The issue on audio id seemed good already on my end but I noticed that we can modify the value of main service to any existing or used value already with a red checkmark BUT with an enabled update button.

v1: https://www.loom.com/share/2c0fa952936640c5ab17698185ec95c0
v2: https://www.loom.com/share/2a24a8be51fc418d85f13789679267f3
v3: https://www.loom.com/share/0f061d54215e4549a0c92062d544133c

**Review by darlp5589 — APPROVED** [review]
After set of repeated testing, I consider this good and approved!

**Pull request merged**
