### PR TITLE
Justin_AlarmSection-AlarmConfig_1202657659482309

### PR DESCRIPTION
**Pull request by pauljustinhernandez**
ASANA ticket: https://app.asana.com/0/1202767126145337/1202818970595348/f

**FULL IMPLEMENTATION OF ALARM CONFIGURATION SECTION**

Description:
- As a user, I should be able to navigate to the Alarm config section
- As a user, I should be able to see the list of configurations
- As a user, I should be able to update the data per configuration, and I should be able to save it in bulk
- As a user, I should be able to revert my changes
- As a user, I should be able to reset the alarm config to defaults
- As a user, I should be able to observe the dynamic enabling of buttons if there are any changes in the given fields
- As a user, I should be able to set timeOutMillis in seconds and convert it back to milliseconds upon saving.
- As a user, I should be able to observe the validations in the timeOutMillis field (numbersOnly, maxLength, min and max)
- As a user, I should be able to see a confirmation modal before and after saving/updating the data including error confirmation.
- As a user, I should be able to observe the dynamic breadcrumbs in the Alarm Section; ~ reference ticket here https://app.asana.com/0/1202364707885489/1202696368125285/f

cc: @triveni-codev @darlp5589 @chriscodev

### CODE REVIEW

**Comment by chriscodev** [comment]
hi @pauljustinhernandez ,

here are my review on this PR 

[PASSED] 	- As a user, I should be able to navigate to the Alarm config section 

[PASSED] 	- As a user, I should be able to see the list of configurations

**[FAILED]** 	- As a user, I should be able to update the data per configuration, and I should be able to save it in bulk
			- see attached image qa1

[PASSED] 	- As a user, I should be able to revert my changes

[PASSED] 	- As a user, I should be able to reset the alarm config to defaults

[PASSED] 	- As a user, I should be able to observe the dynamic enabling of buttons if there are any changes in the given fields

**[FAILED]** 	- As a user, I should be able to set timeOutMillis in seconds and convert it back to milliseconds upon saving.
			- see attached image qa2

**[HOW TO VALIDATE?]** - As a user, I should be able to observe the validations in the timeOutMillis field (numbersOnly, maxLength, min and max)

[PASSED]	- As a user, I should be able to see a confirmation modal before and after saving/updating the data including error confirmation.

[PASSED] 	- As a user, I should be able to observe the dynamic breadcrumbs in the Alarm Section; ~ reference ticket here https://app.asana.com/0/1202364707885489/1202696368125285/f
qa1
qa2

**Comment by pauljustinhernandez** [comment]
Hi Tian  @chriscodev , may I request to see the payload or any sample simulation for the **FAILED** scenarios?

RE: How to validate ~
- field should only accepts natural numbers (1-9)
- field should have a max length of two(2) digits
- field should only accepts a value from 1-99
- consider the copy paste scenario and field suggestion

**Comment by pauljustinhernandez** [comment]
Hi Tian @chriscodev , your last comment on this PR has been fixed. Can pull the branch and re-test it anytime. Thankyyyy

**Comment by chriscodev** [comment]
hi @pauljustinhernandez ,

Here are new updates on my review

[FAILED] - As a user, I should be able to update the data per configuration, and I should be able to save it in bulk
		- see attached image qa_1

[FAILED] - As a user, I should be able to set timeOutMillis in seconds and convert it back to milliseconds upon saving.
- see attached image qa_1

[PASSED] - As a user, I should be able to observe the validations in the timeOutMillis field (numbersOnly, maxLength, min and max)

QA1
qa_1

**Comment by chriscodev** [comment]
Hi @jus,

previous concerns are now solve,

here are the new review comments on the PR

-qa1
    - when addding a new ATSC3  UDP output it gets the nic data and retrieves it on the select field
    - but when selecting a new transport, select field is hidden, this should not be hidden


qa2
    - when retrieving data, notice on console name property is on error, this should not be error
     cause along the way this will create new bug

=========================

Qa1
qa1

Qa2
qa2

**Review by chriscodev — APPROVED** [review]
LGTM

**Comment by triveni-codev** [comment]
Merging this PR to master as approved. 

Additional outlier but supporting note(s):
1. ECMAscript 2019 was added in tsconfig library.
2. PR #457 was intentionally added as merge pre-requisite first before this.

~~~~~
Alarms section: Functionality implementation to allow bulk update of Alarms Config when Apply button is pressed
https://app.asana.com/0/1201468220173184/1202818970595348/f

**Pull request merged**
