### PR TITLE
chrisdev_deleteElemStream_1203287929531879

### PR DESCRIPTION
**Pull request by chriscodev**
Hi @triveni-codev ,

ASANA TICKET: Transports Section continuous improvement
https://app.asana.com/0/1202364707885466/1203287929531879

to test:

> from server data: 

- able to delete elementary  stream and update programs table and able to commit
- able to delete elementary stream and cancel does not update program table and able to commit
- 
- newly added elementary stream and delete and update programs table and able to commit
- newly added elementary stream and cancel does not update program table and able to commit

> newly added transport
- able to add newly added elementary stream then delete and update programs table and able to commit
- able to add multiple elementary stream and delete them and and update programs table and able to commit

let me know if you have concerns, this is ready for testing.

Cheers,
Christian

### CODE REVIEW

**Comment by triveni-codev** [comment]
Assigning main reviewer task as this hasn't gained traction: @darlp5589 
Newly generated code conflicts are minor but kindly include it in the review.

**Comment by darlp5589** [comment]
Got this. Will do.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking PR. Here are my concerns: 

1. i1: Delete confirmation box message is different from Java App for MPEG type. 
2. i2: I was about to update an elementary stream when I tried to update the id of same value, that error message shows up and can't proceed on editing the other details.
3. i3: I was able to add 2 MPEG type however, I can't replicate anymore though but just check this scenario for possible recurrence.
4. i4: I'm about to create a new transport then new program. That shows up in the console.



i1: 
image

i2: 
image

i3: 
image

i4:  
image

**Comment by chriscodev** [comment]
Hi @darlp5589 , 

new  update on my branch, you may now  retest on your end.


i1: Delete confirmation box message is different from Java App for MPEG type. [DONE]

i2: I was about to update an elementary stream when I tried to update the id of same value, that error message shows up and can't proceed on editing the other details. [DONE]

i3: I was able to add 2 MPEG type however, I can't replicate anymore though but just check this scenario for possible recurrence. [DONE]

i4: I'm about to create a new transport then new program. That shows up in the console.[DONE]

Cheers,
Christian

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking PR fixes. Here are my concerns:

1. i1: I can add 2 MPEG-2 Stream Types. To reproduce, have a transport from server with existing MPEG Elementary Stream record then try to update it but cancel. Now add another record with AC-3 Audio. Now if you add again another record, MPEG-2 Stream is now enabled. This is also happening on newly created transport with newly created services.
2. i2: I still can receive an error message saying PID already exist after I updated a record and simply changing the current PID to the same PID number.



i1: 
image

i2: 
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking fixes. They are good. I have one concern though.

1. i1: I created a new transport, added a program number 1 then added program number 2. When I updated program number 2 ang clicked OK, program number 1 becomes program number 2.



i1: 
image

**Comment by triveni-codev** [comment]
Hi @chriscodev , there's a new overlay of minor code conflict prompt after I merge a previous PR (PR #501). Kindly verify. thanks

**Review by darlp5589 — APPROVED** [review]
Done checking fix. LGTM! 

Thanks!

**Comment by triveni-codev** [comment]
Merged as approved. Code conflict sorted out. Final checks carried out in addition, that fixed the issue that caused the less desirable change from 'number' to 'any' of markOrigPID variable instantiation.

**Pull request merged**
