### PR TITLE
chrisdev_atsc3transport_1202281468766893

### PR DESCRIPTION
**Pull request by chriscodev**
[Bug] Transports Section: DataTable error pop-up on first load

### CODE REVIEW

**Comment by triveni-codev** [comment]
Bug fix confirmed for [[Bug] Transports Section: DataTable error pop-up on first load](https://app.asana.com/0/1202249852885599/1202309387297201/f). However you have included in this  PR the initial fragments of Edit recovery settings development and I cannot merge it without affecting the other ticket.
Bug fix changes:
image

~~~~~~
[Bug] Transports Section: DataTable error pop-up on first load
https://app.asana.com/0/1202249852885599/1202309387297201/f

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Here are my feedbacks based on comparing set of test values from client app as well as features from client app:

1. in image1, password field isn't set as input type=password
2. in image1, username isn't pulled from the server
3. in image1, password should have a magnifying glass beside it as a toggle to view the password or not based from client app
4. in image1, submission url checkmark isn't in green even if it's a valid url. To reproduce it, try to erase the url being pulled from server then close the edit recovery settings modal and open it, it won't pull the url from server (which is another issue). To pull the url from server, you need to close the service group modal and reopen it then click the recovery settings button, it pulls the url but the checkmark is black.
5. editing the value of any fields in recovery settings modal then closed that modal (not saving), it will also edit the value which shouldn't be since a close / cancel button is clicked.
6. in image2, submission url default value on newly added service group isn't set
7. in image2, submission url checkbox is in green even if no default value is being specified
8. OK button isn't working for recovery settings modal


image1: 
image

image2:
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
After reviewing changes/fixes based on last feedbacks, here are our pending items:

1. submission url default value on newly added service group isn't set
2. submission url checkbox is in green even if no default value is being specified
3. OK button isn't working for recovery settings modal
4. password should have a magnifying glass beside it as a toggle to view the password or not based from client app

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done with review. Here are pending concerns:

1. submission url default value on newly added service group isn't set (you can reproduce this by adding new service group and click on an empty recovery settings then compare with the client app)
2. submission url checkbox is in green even if no default value is being specified 
3. in image1, enabled ESG checkmark is clicked but the fields are disabled
4. in image1, destination address will still accept invalid ip address format
5. in image2, after doing some updates on ESG Settings Modal and clicked OK button, field values being pulled from server for AEA Settings were cleared. This also happens to other settings modal wherein an update on a particular settings modal will trigger to clear the field values of other settings modal. Hard to replicate on some.
6. AEA settings changes will revert after clicking OK button

image1:
image

image2:
image

**Comment by chriscodev** [comment]
- test only update data way through commit from lls, aea,esg,broadband,
recovery settings
- v1 embedded not yet functioning [recovery]
- add-edit and add functionality service is not yet functioning
- update/edit button ok is functioning like after passing data
- eye password implemented
- review comments fix

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Here are my pending concerns:

1. in image1, enabled ESG checkmark is clicked but the fields are disabled
2. in image2, destination address will still accept invalid ip address format
3. AEA settings changes will revert after clicking OK button
4. Issue on Edit AEA Settings field values being cleared after clicking OK button of ESG Settings modal still persist.
5. Issue on Edit Broadband Settings field values being cleared after clicking OK button of Recovery Settings modal still persist.

image1: 
image

image2:
image

**Comment by chriscodev** [comment]
[2032149](https://github.com/triveni-codev/GBWebApp-dev/pull/431/commits/20321499637b290aa9af2581d192da1af4db1163)

PR concerns fixes:
- in image1, enabled ESG checkmark is clicked but the fields are disabled
- in image2, destination address will still accept invalid ip address format
- AEA settings changes will revert after clicking OK button
- Issue on Edit AEA Settings field values being cleared after clicking OK button of ESG Settings modal still persist.
- Issue on Edit Broadband Settings field values being cleared after clicking OK button of Recovery Settings modal still persist.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Pending PR concerns:

1. image1: destination address concern before was fixed however pulling a valid address from server and opening ESG settings modal for the first time w/o touching will have the checkmark in red.
2. Issue on Edit Broadband Settings field values being cleared after clicking OK button of Recovery Settings modal still persist. Please take note that clicking OK button on Edit Broadband Settings will also trigger to clear values of Recovery Settings fields. They are vice versa at some point.

image1:
image

**Comment by chriscodev** [comment]
COMMIT: Pending PR concerns:

image1: destination address concern before was fixed however pulling a valid address from server and opening ESG settings modal for the first time w/o touching will have the checkmark in red.
Issue on Edit Broadband Settings field values being cleared after clicking OK button of Recovery Settings modal still persist. Please take note that clicking OK button on Edit Broadband Settings will also trigger to clear values of Recovery Settings fields. They are vice versa at some point.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done testing. Here are my pending concerns:

1. Issue on Destination Address on ESG Settings modal still persist.
2. I encountered data table warning every time I saved my changes for the test service group.

image:
image

**Review by darlp5589 — APPROVED** [review]
No pending concerns left! Party2!:D

**Pull request merged**
