### PR TITLE
Darlp networks service descriptor 1203527428612576

### PR DESCRIPTION
**Pull request by darlp5589**
Hi @triveni-codev @chriscodev @pauljustinhernandez 

Kindly check this PR for Service Descriptors. This is only for ATSC Cable and ATSC Terrestrial Types (don't test the ATSC 3)

ASANA: https://app.asana.com/0/1201943683850147/1203527428612576

TO TEST:
-logics on toggling valid/invalid values
-lazy loading implementation (shouldn't be loaded unless if modal is called)
-logic for extended channel name (once added, you can't add another instance) 
-logic for redistribution control descriptor type (once added, you can't add another instance also can't be updated)
-draft values being closed/cancelled should be good including the parent set of modals
-adding of one or more descriptor types (dirty change)
-updating of one or more descriptor types (dirty change) 
-retrieval of existing data from server is already displayed properly and can be added or updated with one or more descriptor types
-big commit for ADDING SERVICE DESCRIPTOR

DON'T TEST: Big Commit for UPDATING SERVICE DESCRIPTOR

### CODE REVIEW

**Comment by chriscodev** [comment]
hi @darlp5589 , 

here are my review comments on PR:

   ====================

   qa1
   when i tried adding a new network and try to add a new service descriptor
   and i add them all, on the  atsc channel modal the atsc service button is disabled and i can add another atsc service

   qa2
   select component is not same with other component same on the text
    
    qa2a
    table component is not same with other component issue with with the text


qa3

on existing data on atsc service and 
 add another atsc channel
 and add a new service descriptor [redistribution channel] click ok
then add another atsc channel and the [redistribution channel] on select is gone
qa1
qa2
qa2a
qa3
qa4


another scenario
- on  adding service then add a service descriptor successfully it is added in the table in service modal then i click cancel then add again atsc service then service descriptor redistribution channel is gone


qa4
  after clicking ok this is displayed then gone in a milisecond, this should not display

**Comment by darlp5589** [comment]
Hi @chriscodev ,

Here are my updates:
qa1: Good as fine based on convo.
qa2: Leave as is based on convo. Will work on the fa css once all descriptors/extensions are good.
qa3: Fixed.
qa4: Fixed.

**Review by chriscodev — APPROVED** [review]
LGTM

**Comment by darlp5589** [comment]
Just noticed I haven't formally sent my request here (only in Slack) so I'll just do so. 

@chriscodev , kindly check big commit for updating service descriptors for atsc cable/terrestrial. Thanks!

**Comment by chriscodev** [comment]
hi @darlp5589 , 

This Looks good to me, i can update and do big commit on service descriptors.

Cheers,
Christian

**Pull request merged**
