### PR TITLE
Justin_AlarmSection-FilterSearch_1202601797867695

### PR DESCRIPTION
**Pull request by pauljustinhernandez**
ASANA ticket : https://app.asana.com/0/1202364707885489/1202601797867685/f

- Implemented search filter for the Active Alarms and Alarm History Module
- This is a dynamic filter search
- Created an Akita state for the Active Alarms and Alarm History

### CODE REVIEW

**Comment by triveni-codev** [comment]
Cleanly resynced with Master branch to reduce files changed from 50 to 20.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done reviewing this PR. Below are my concerns:

1. image1: For some reason we have a counter of 6 but no entries available. Not sure what happened here but please just check. This is considering I have no entries for transport, networks and outputs. It was then updated to 1 after I added an output w/o a transport.
2. image2: Not sure if this was a concern being raised before but I modified the output name in the ClientApp but didn't reflect in the WebApp after doing commit.
3. image2: I understand the 3 of them belong to a one type that says OUTPUT_NO_TRANSPORT but the description are different though it seemed to have the same context. Do you think it's fine to have a uniform description?
4. image3: Maybe it's better to automatically apply when Reset Filter button gets clicked w/o the need to click on Search button. Based on the screenshot alone, it can confuse someone as to why there are counts above but no associated entries (this is different from concern #1) considering no visible filters being applied here. To reproduce, entries were there but added some filters that were not in any of the entries thus no results were displayed then clicked Reset Filter button w/o clicking Search button. 
5. image4: this is in relation to image3, so we have 4 entries by default for filters: level='information' and type='output no transport'. When I attempted to change type='stream no data' (or any other types) w/o clicking the Search button then updated something in the client app (that should remove an entry in the web app) then clicked commit, the web app receives the update and refreshes the entries to 3 already but the type is still 'stream no data' and it seemed that those entries are under that type when they shouldn't. What I'm saying is, maybe we should just remove the search button and automatically apply any changes on the type or level dropdown.

image1: 
image

image2: 
image

image3: 
image

image4: 
image

**Comment by pauljustinhernandez** [comment]
1. ) Will check on this.
2.) Yes Darl, it was already raised to Dave. Please see my last message in slack #general channel FYR to this.
3.) My initial insight is that **DESCRIPTION** is basically composed of a long string which can be an explanation why the alarm occurred. While on the other hand, **TYPE** is basically an alarm type. In any case, this is a backend thing, and can be discussed with Dave next meeting.
4.) This is a great observation Darl! Thanks for this, I'll make some changes for this.
5.) I don't think this is a good idea Darl, calling the filter search function everytime the user selects in the dropdown is somehow a heavy approach. We should use a lazy loading approach to avoid a heavy data interpolation.

@darlp5589

**Review by darlp5589 — APPROVED** [review]
Hi @pauljustinhernandez  after reviewing, I can confirm all concerns are fine except for those that needs further approval or talk on Dave/Jan's end. This is approved for now. :)

**Comment by triveni-codev** [comment]
@pauljustinhernandez,

Before this gets merged, kindly update the non-uniformed spacing that is going on between the filter label and the dropdown/textfield component in the search filter panel.

**Comment by triveni-codev** [comment]
Changes confirmed. Sorted out code conflict found. PR has been merged to master
~~~~~~~~
Filter Active Alarms table view via "Level" category search filter
https://app.asana.com/0/1202364707885489/1202601797867685/f

**Pull request merged**
