### PR TITLE
Justin_OutputsSection-DirtyCRUDoperation_1202710413029925

### PR DESCRIPTION
**Pull request by pauljustinhernandez**
ASANA ticket: https://app.asana.com/0/1202657659482238/1202710413029925/f

Description:
- Implemented the remaining dirty Add -> Edit operation in Output Section
- Fixed the bug correlates to this ticket - https://app.asana.com/0/1200797465348879/1200788949514881/1202698308225447
- Fixed lint issues
- Removed unnecessary codes

### CODE REVIEW

**Comment by chriscodev** [comment]
hi @pauljustinhernandez ,

here are my review comments on this PR

qa1
on add output 
    - cant proceed to adding output triveni type,
    - add button is disabled when validations are valid

qa2
    on add output 
    - cant proceed to adding output atsc3 type,
    - add button is disabled when validations are valid


===============

qa1
qa1


qa2
qa2

Cheers,
Christian

**Review by chriscodev — CHANGES_REQUESTED** [review]
I have some feedbacks on the PR

**Comment by chriscodev** [comment]
Hi @Paul Justin Hernandez, for this qa this is only focus on ATSC.3 type

qa1
	- on add then edit ATSC3.0 updatebutton is disabled when fields are valid


qa2
	- can alraeady add, but when enabling source port field
	add is disabed

qa3

	- on server data
		on update when source port is availabe try to edit or change data
		button will be disabled, it should be enabled

qa1
qa1

qa2
qa2

qa3
qa3

**Comment by chriscodev** [comment]
hi @pauljustinhernandez ,

Here are my comment on this PR: 

qa1 - on add then edit ATSC3.0 updatebutton is disabled when fields are valid , to be same in clientApp

qa2 - on server data, on editing an output and selecting a tranport, seems add button is disable



===================

qa1
qa1


qa2
qa2


Cheers,
Christian

**Comment by pauljustinhernandez** [comment]
Hi Tian @chriscodev see my inputs below Re your last comments in this PR

**qa1** - Upon checking in our angular app, we have this function called **markOriginalOutput** which checks the data if it is in original state or not. That's why the update button is in disabled mode at first, and it will be enabled when the user change any of the data. But you are right that upon checking the java clientapp, there's no similar validation. I think we should discuss this with Jan?

**qa2** - see this loom clip FYR https://www.loom.com/share/0e36a6b8ccca49e7857462b34a191886

cc: @donjebc

**Comment by chriscodev** [comment]
Hi @pauljustinhernandez ,

other concerns are now fixed, but another issue occur see, attached image

qa1	- this should be a select dropdown with selected value

qa2 - cant proceed to commit due to error
      - this caused when data is passed differently on api call
	- try using post man for the right data to be past on api

======================
QA1
qa1


QA2
qa2

Cheers,
Christian

**Comment by chriscodev** [comment]
Hi @jus,

previous concerns are now solve,

here are the new review comments on the PR

-qa1
    - when addding a new ATSC3  UDP output it gets the nic data and retrieves it on the select field
    - but when selecting a new transport, select field is hidden, this should not be hidden


qa2
    - when retrieving data, notice on console name property is on error, this should not be error
     cause along the way this will create new bug

qa1
qa2

**Comment by chriscodev** [comment]
Hi @pauljustinhernandez ,

here are my concerns when adding Outputs

qa
	- when adding
		-add outputs then next button
			- try to select add button on select transport then cancel on the modal without doing anything
			-then try to add button on ATSC UDP Output
			- it does not capture nic data there fore causing the api to error
			
qa1


Cheers,
Christian

**Review by chriscodev — CHANGES_REQUESTED** [review]
remove unused lines codes or commented lines of codes and also the console logs, i think after the new updates will approve on my end.

**Comment by triveni-codev** [comment]
Bump @pauljustinhernandez

**Comment by triveni-codev** [comment]
Dear @chriscodev,

image

**Review by chriscodev — APPROVED** [review]
LGTM

**Comment by triveni-codev** [comment]
Merging this PR as approved.

~~~
Outputs Section development kickstart for Justin: Implementation of remaining dirty Add -> Edit operation
https://app.asana.com/0/1202657659482238/1202710413029925/f

**Pull request merged**
