### PR TITLE
Justin_SW-Update-Code-Restoration_1203070012440446

### PR DESCRIPTION
**Pull request by pauljustinhernandez**
ASANA ticket: https://app.asana.com/0/1203010733158020/1203070012440446/f

Description:
- restored the initial code for the SW Update function to fix the issue

### CODE REVIEW

**Comment by triveni-codev** [comment]
Thank you Darl. Right now, I'm temporarily removing this from your plate for re-balancing.

**Comment by darlp5589** [comment]
Got this and noted @triveni-codev . Thanks!

**Comment by triveni-codev** [comment]
Re-balanced and assigned back to Darl for streamlined continuity

**Review by darlp5589 — APPROVED** [review]
Changes look good to me! Approved.

**Comment by triveni-codev** [comment]
Commencing merge.
 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 On other note, I'll use this opportunity as an example of my exposition,
 
     Re: Sprint retrospective remarks & improvement on the floor height of code quality regardless if old code or not ~ If I channel the overthinker & peak "no stones left unturned" side of me in terms of quality of life changes, my final checks led me to some additional inquiries & additional review comments to improve abstraction of the codes.
 
     The "Don't stress the small things" side of me would say its alright, this and that.... in the grand scheme of things. Because of this, I don't spread myself thin, I compromise, I understand and I find a good middle ground for a better & sustainable workplace (Without compromising the team's quality and work ethic of course). Thought I'd let you all know about some of the things I weigh in & why I think the way I think, before merging.
     
     Figuratively, If things tip off to one side for the worse i.e.: If the team's floor of value & quality stagnates and declines, I'd be forced to take extreme measures. Individual freedom and coasting would be affected and that's not what we want.
  
    If anything, I hope the complete notion above will veer towards why I try to find equilibrium, why I bank on not providing extrinsic factor aka motivation and why vaguely, comparison is the thief of joy (within the right context).
    
On that note, thank you for the work team.

@darlp5589 @pauljustinhernandez @chriscodev 
  
 

~~~~~~~~~~~~~~
[Fix required] Issue found on the recently occurring software update activity that failed unexpectedly
https://app.asana.com/0/1203106518351809/1203070012440446/f
Source PR: https://github.com/triveni-codev/GBWebApp-dev/pull/474

**Pull request merged**
