### PR TITLE
Darlp networks 1202522746056213

### PR DESCRIPTION
**Pull request by darlp5589**
Hi @triveni-codev , @chriscodev 

Here are the ASANA Tickets being associated for this PR:
1. https://app.asana.com/0/1201943683850147/1202522746056213
2. https://app.asana.com/0/1201943683850147/1202551313941903
3. (To follow: Transport Links Dirty Change handling) <- this incoming ticket is already implemented both for dirty change and from server

Here are the detailed instructions to check:
1. UI for adding ATSC3 network type should be same with ClientApp
2. Functionalities/Features should be same flow with ClientApp and reused existing methods from other ATSC types (modals, sequence, x/cancel button, ok button, prev button)
3. Most data passing is reused from other ATSC types
4. Dirty change handling should be working properly both Add and Update functionalities from Network, Channel and Transport Links
5. Updates from server returned ATSC3 type networks should be working properly as well
6. Big Commit Features should be working on the following:
   a. can ADD one or more new networks with ATSC3 type
   b. can ADD one or more new networks with ATSC3 type and one or more Channels
   c. can ADD one or more new networks with ATSC3 type and one ore more Channels with Transport Links
   d. can UPDATE one or more new networks with ATSC3 type
   e. can UPDATE one or more new networks with ATSC3 type and one or more Channels
   f. can UPDATE one or more new networks with ATSC3 type and one ore more Channels with Transport Links
   g. can ADD and UPDATE one or more new networks with ATSC3 type
   h. can ADD and UPDATE one or more new networks with ATSC3 type and one or more Channels
   i. can ADD and UPDATE one or more new networks with ATSC3 type and one ore more Channels with Transport Links
   j. can combine ADD / UPDATE ASTC3 network Type along with other ATSC network types.

7. Please take note that Extensions array isn't included in this ticket yet.

### CODE REVIEW

**Comment by chriscodev** [comment]
hi @darlp5589 ,

Here are the review comment:

 i cant proceed to other functionalities since i cant procced to other steps.

image 1. when opening ATSC channel  select2 is error
     and cant click ok button since select option is invalid

see image below
img1
img1

**Comment by darlp5589** [comment]
> hi @darlp5589 ,
> 
> Here are the review comment:
> 
> i cant proceed to other functionalities since i cant procced to other steps.
> 
> image 1. when opening ATSC channel select2 is error and cant click ok button since select option is invalid
> 
> see image below img1 img1

Kindly recheck. This can be fixed by running npm i on your cli.

**Review by chriscodev — APPROVED** [review]
LGTM

**Comment by triveni-codev** [comment]
Commencing PR merge. Other changes added on top of Tian's review has been confirmed. Namely,
1. fixed lint issues on all network related components that I have worked so far
2. Converted all tab indented components to space settings then modified the linting to only allow space indentation
3. (not a review comment) Fixed minor code conflict that should have been taken cared of by git itself


~~~~~~~
Linked ASANA tickets:
1. [ATSC3 Network Type: Implementation & UI development to allow commit operation of simple dirty change](https://app.asana.com/0/1201943683850147/1202522746056213)

2. [ATSC3 Channels dirty change handling development](https://app.asana.com/0/1201943683850147/1202551313941903)

3. [ATSC3 Transport Links dirty change data handling](https://app.asana.com/0/1202505610483705/1202657659482320/f)

**Comment by triveni-codev** [comment]
Linked ASANA tickets:
1. [ATSC3 Network Type: Implementation & UI development to allow commit operation of simple dirty change](https://app.asana.com/0/1201943683850147/1202522746056213)

2. [ATSC3 Channels dirty change handling development](https://app.asana.com/0/1201943683850147/1202551313941903)

3. [ATSC3 Transport Links dirty change data handling](https://app.asana.com/0/1202505610483705/1202657659482320/f)

**Pull request merged**
