### PR TITLE
chrisdev_serviceGrpDeletion

### PR DESCRIPTION
**Pull request by chriscodev**
Hi @triveni-codev ,

This is a continues transport integration and
this branch is a branchout of 
chrisdev_bugTransportCommit_1203318703397642 - https://github.com/triveni-codev/GBWebApp-dev/pull/495 

this is a branch in where transport can delete service groups

to test -  
from server data
	can delete multiple service group service group
	can delete service group then prev then next
	can delete service group then cancel can still retrieve previous data

newly added transport  data
	can add service group then delete

### CODE REVIEW

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking this PR. Here are my concerns:

1. Not sure if Big Commit is already part of this PR but I have added a new transport and 1 service group which I deleted right away. The big commit button is already enabled but nothing to be committed since I just deleted what I just added.
2. i1: Make the casing consistent with Java App.
3. I have a transport from server with 1 service group. Updated that transport and deleted the service group then clicked cancel/close. I have updated that transport again, the service group is still there (which is correct) but when I try to add new service group, it will overwrite the existing one.
4. I have an existing transport w/ service group from server, updated it and added a service group then removed the existing one and clicked update button. I updated  that transport again, go to service group modal and noticed only the newly added service group is there (which is correct) but when I clicked update button then opened that transport again, that newly added service group was gone.



i1: 
image

**Comment by chriscodev** [comment]
hi @darlp5589 , @triveni-codev 

just and update  on this fix

- Not sure if Big Commit is already part of this PR but I have added a new transport and 1 service group which I deleted right away. The big commit button is already enabled but nothing to be committed since I just deleted what I just added.

[this will be a separate ticket: since this is a big scope on the commitbutton , it is when reverting data it to original one, since this has a lot of data to to look into like the properties and  string/numbers to be checked]

- i1: Make the casing consistent with Java App. [updated]

- I have a transport from server with 1 service group. Updated that transport and deleted the service group then clicked cancel/close. I have updated that transport again, the service group is still there (which is correct) but when I try to add new service group, it will overwrite the existing one.[updated]

- I have an existing transport w/ service group from server, updated it and added a service group then removed the existing one and clicked update button. I updated that transport again, go to service group modal and noticed only the newly added service group is there (which is correct) but when I clicked update button then opened that transport again, that newly added service group was gone.[updated]

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking PR fixes. Here are my concerns: 

1. v1: I have a transport form server with existing service group. Updated it and deleted the service group then clicked close/cancel. I then updated that transport again (that deleted service group is still there which is correct), then added a new service group and clicked update. On my last attempt to update the transport, I noticed that only the newly added service group is there.
2. v2: My previous concern is still there -> I have an existing transport w/ service group from server, updated it and added a service group then removed the existing one and clicked update button. I updated that transport again, go to service group modal and noticed only the newly added service group is there (which is correct) but when I clicked update button then opened that transport again, that newly added service group was gone



v1: https://www.loom.com/share/5ed57adc11464753bd22595ed68bcc43
v2: https://www.loom.com/share/285bc520990142ea86392dc186f4a8c5

**Comment by chriscodev** [comment]
hi @darlp5589,

I have new updates on this PR, you may now verify on your  end:

v1: I have a transport form server with existing service group. Updated it and deleted the service group then clicked close/cancel. I then updated that transport again (that deleted service group is still there which is correct), then added a new service group and clicked update. On my last attempt to update the transport, I noticed that only the newly added service group is there. **_[updated]_**


v2: My previous concern is still there -> I have an existing transport w/ service group from server, updated it and added a service group then removed the existing one and clicked update button. I updated that transport again, go to service group modal and noticed only the newly added service group is there (which is correct) but when I clicked update button then opened that transport again, that newly added service group was gone **_[updated]_**

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking PR fixes. Here are my concerns:

1. v1: previous concern -> I have a transport form server with existing service group. Updated it and deleted the service group then clicked close/cancel. I then updated that transport again (that deleted service group is still there which is correct), then added a new service group and clicked update. On my last attempt to update the transport, I noticed that only the newly added service group is there. 
[THIS IS FIXED ALREADY. HOWEVER, IF YOU CLICK ON UPDATE AGAIN W/O CHANGING ANYTHING, IT WILL AUTOMATICALLY DELETE THE EXISTING SERVICE GROUP]
2. v2: My previous concern is still there -> I have an existing transport w/ service group from server, updated it and added a service group then removed the existing one and clicked update button. I updated that transport again, go to service group modal and noticed only the newly added service group is there (which is correct) but when I clicked update button then opened that transport again, that newly added service group was gone


v1: https://www.loom.com/share/f9e20c22e8694226a9810a4806be65ad
v2: https://www.loom.com/share/285bc520990142ea86392dc186f4a8c5

**Comment by chriscodev** [comment]
hi @darlp5589 , apologies for this dancing PR, found out previous implementation is not ok, this  new comment fixes the concern now, you may now verify on your end.

commit: https://github.com/triveni-codev/GBWebApp-dev/pull/512/commits/4f3460ec1598735a9a5eb99fe4e3f8817eafa3bd

Thanks,
Christian

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Checked on the PR fixes and I can confirm that they are already good except that I discovered something along the way that is not part of delete service group scope but a serious bug.

v1: I created a new transport, and added 2 group service. Once I started updating a group service, instead of updating the original one, it will create a new instance of updated group service.

v1: https://www.loom.com/share/070653821d914dd1b8d37edc27d7c516

**Pull request merged**
