### PR TITLE
Justin_Revamp-hardcoded-1.8seconds-delay_1203161913149875

### PR DESCRIPTION
**Pull request by pauljustinhernandez**
ASANA ticket: https://app.asana.com/0/1203173080108752/1203161913149875/f

Description: Implemented dynamic delay for the page navigation/routing

### CODE REVIEW

**Comment by pauljustinhernandez** [comment]
**To test via GBWebapp local:**
- As a user, when data tables are currently loading, I should not be able to use click events on the page, including navigation/routing

**To test via GBWebapp VM:**
- build a local copy of your GBWebapp via `npm run build`
- paste it inside your VM
- access your GBWebapp via VM
- Test the scenario mentioned above ^^ especially the sidebar navigation

**Comment by triveni-codev** [comment]
@pauljustinhernandez ,

Upon quick checking of your codes, the implementation is nice and well. However, this seems to be not an end to end implementation (Sidebar section/component <-> main UI portion of each section communication). 
The isMainTableLoading should only act as sort of an API that the sidebar section depends on.

What would happen with this implementation is that, everytime a new section is created (example: Mediastream section), a developer has to be mindful and go through a bit hoops and loops to implement this same pattern for this to work in the same behavior with the rest.

What could be taken look at is that, even if a new section/component is added, a developer won't have to think of this. 

Kindly check if you can implement an end to end communication where your focus(on your end) is just to make the sidebar section/component work better (with the help of isMainTableLoading state that came from the other end). This was essentially the purpose of the ticket.

If there's anything that I should be enlightened with from your investigation, let me know.

**Comment by pauljustinhernandez** [comment]
Acknowledged Jan @triveni-codev . gonna make an amends for this after the PR review task. Thanks!

**Comment by triveni-codev** [comment]
From further deliberation & earlier discussion of the implementation implications including the code adjustments laid on top, this has been reconsidered and admitted. Thanks for the collaboration.


-----------------------------
Assigning main reviewer: @darlp5589

**Comment by darlp5589** [comment]
Hi @pauljustinhernandez , upon checking, I noticed it's fine on all side menus that has dropdowns (alarm, notifications, server settings, status) since it will take some time to switch to a new page as you have to go through dropdown options and select. However, there is an issue associated with a console error specifically on the side menus that are directly clickable like the Dashboard and the Network Config. See vid below:

https://www.loom.com/share/508bf3f413d34ab78f1fa5f4a6d3d6f2

**Review by darlp5589 — APPROVED** [review]
Done checking PR fixes. I can confirm that the fix is already working. I have approved this then.

**Pull request merged**
