### PR TITLE
chrisdev_modalPSIdefault_1203287929531879

### PR DESCRIPTION
**Pull request by chriscodev**
hi @triveni-codev , @darlp5589 , @pauljustinhernandez 

ASANA TICKET: https://app.asana.com/0/1202364707885466/1203287929531879

Just an update on this branch to test

check all form from PSIP and PSI modals and form for validation and check if successfull update
	toggle PSI Enabled
	PSI open Modal
		- check all form is valid
		- on click update is successful
		- check default button to bereverted back to its original form

	PSIP open Modal
		- check all form is valid
		- on click update is successful
		- check default button to bereverted back to its original form

- not able to connect data to commit, since this is my blocker
	checked the code on api swagger but could not found proper data to be attached in API on send data

### CODE REVIEW

**Comment by chriscodev** [comment]
hi @triveni-codev ,

new updates on  this  PR.

ASANA TICKET: https://app.asana.com/0/1202364707885466/1203287929531879

this is  also a fix  for the PSI modal bug,
chrisdev_bugPSI_1203388324315561 #507
https://github.com/triveni-codev/GBWebApp-dev/pull/507 [closed]

========
things to check on PSIP-TERRESTRIAL
	- can add PSI SETTING
	- can retrieve and update PSI SETTING 

	- can add PSIP SETTING
	- can retrieve and update PSIP SETTING 

on import
	-can add PSI SETTING
	-can retrieve and update PSI SETTING 

	-can add PSIP SETTING
	-can retrieve and update PSIP SETTING 


Cheers,
Christian

**Comment by triveni-codev** [comment]
Dependency file needed to reach the PSIP and PSI settings in Import Transports Functionality
[TransportExpTest.csv](https://github.com/triveni-codev/GBWebApp-dev/files/10129966/TransportExpTest.csv)

**Comment by pauljustinhernandez** [comment]
Hi Tian @chriscodev , dropping here the ff. concerns;
1. number fields should not allow whitespaces (both in PSI and PSIP)
bug1-number fields should not allow space

2. app does not store changes made after update (both in PSI and PSIP)
bug2-app does not store changes made in the PSI setting

3. PSI defaults button should remain enable
bug3-PSI defaults button should remain enable

**Comment by chriscodev** [comment]
hi @pauljustinhernandez 

just an update on this task, you may now test the new updates on this branch


1. number fields should not allow whitespaces (both in PSI and PSIP)[this is alread update]
2. app does not store changes made after update (both in PSI and PSIP) [done]
3. PSI defaults button should remain enable [done]
 
you may now recheck the above concerns

hi @triveni-codev 


i have concern on commiting psi and psip transport before it was working see  attached concern1.jpg
but now i am in the latest svn theissue on the api is not going through see attached concern2. jpg

Concern1
concern1

Convern2
concern2


Cheers,
Christian

**Comment by pauljustinhernandez** [comment]
Hi Tian @chriscodev , dropping here further concerns;

1. number fields should not allow whitespaces VIA COPY PASTE (both in PSI and PSIP)
bug1-whitespace via copy paste

2. app does not store changes made after update (both in PSI and PSIP) ~ there's an undefined error
bug2-app does not store changes made after update

**OTHER MINIMAL CONCERNS (UI):**
1. checkboxes alignment
bug3-checkbox alignment

2. green check validation alignment
bug4-green check validation alignment

**Comment by chriscodev** [comment]
hi @pauljustinhernandez ,

 I have new update on my PR  you may now test it on your end.

Cheers,
Christian

**Comment by pauljustinhernandez** [comment]
LGTM! @chriscodev

**Comment by triveni-codev** [comment]
Merging this PR as approved by main reviewer. Also performed final checks and PR merge issues mitigation.

@chriscodev , I hope the previous issues in PSIP/PSI when adding/updating a Physical Transport gets cleaned up. Since I already reported it before as working ~ during past client meeting.

**Pull request merged**
