### PR TITLE
chrisdev_importTestings

### PR DESCRIPTION
**Pull request by chriscodev**

### CODE REVIEW

**Comment by chriscodev** [comment]
ASANA TICKET: https://app.asana.com/0/1203173080108752/1203187010155059

hi @darlp5589 , @triveni-codev , @pauljustinhernandez , you may now review this PR

note: do not test the function in the PSI DEFAULT BUTTONS this will be on another ticket

Cheers,
Christian

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Checked on this by importing only 1 transport (that I exported from Java app) to both Java and Angular Apps for comparison purposes.

1. i1: It says number of transports exceed license limit which is set to 5 but I currently have 3 transports only. 
2. i2: I compared both apps side by side and marked the difference in the SS.
3. Clicked import button then clicked cancel or close then clicked import button again, I can't anymore see the modal.
4. I imported a PSIP-Cable file but on transport list, it becomes PSIP-Terrestrial.




i1:
image

i2: 
image

**Comment by triveni-codev** [comment]
Tian, kindly update w/ review comments No. 1 to 4 and exercise high-level of caution (I'll be explicitly reminding this to everyone). I'll be asking also on the overlooked cause especially No.2 and No.4.

**Comment by chriscodev** [comment]
hi @darlp5589 ,  

new PR fix on review comments

- i1: It says number of transports exceed license limit which is set to 5 but I currently have 3 transports only. [done]

- i2: I compared both apps side by side and marked the difference in the SS.[done]

- Clicked import button then clicked cancel or close then clicked import button again, I can't anymore see the modal.[done]

- I imported a PSIP-Cable file but on transport list, it becomes PSIP-Terrestrial.[done]

you may now review on your end.

Cheers,
Christian

**Review by darlp5589 — CHANGES_REQUESTED** [review]
As I check to verify PR fixes, I can't proceed because of below concern.

1. i1: I imported the same file I used yesterday and it went blank with a console error on the right. I still can import it in Java File though.

i1: 
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking. Here are my concerns using the same file on both angular app and java apps:

1. i1: Side by side comparison differences.
2. i2: I can import 2 same transport name by importing same file twice. In the Java app, it throws an error already on my 2nd attempt to import the same file.
3. i3: After importing a transport and clicked edit, the TSID value is not in green checkmark.
4. i4: After successful import, edited it and here's a side by side comparison of 2 same transports with programs.


i1: 
image

i2: 
image

i3: 
image

i4: 
image

**Comment by chriscodev** [comment]
Hi @darlp5589 , This is now ready for your review:

i1: Side by side comparison differences. [updated]
i2: I can import 2 same transport name by importing same file twice. In the Java app, it throws an error already on my 2nd attempt to import the same file. [updated]
i3: After importing a transport and clicked edit, the TSID value is not in green checkmark. [updated]
i4: After successful import, edited it and here's a side by side comparison of 2 same transports with programs. [updated]

you may now check on your end.

ASANA TICKET:
https://app.asana.com/0/1203173080108752/1203187010155059

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking. Here are my concerns:

i1: Still the comparison isn't implemented.
i2: I still can import the same file twice with same transport name.
i3: After successfully importing a transport, the checkmark beside TSID is still in black (not consistent with Java App and the checkmark beside name field). Am I safe to assume that this is fine?
i4: Transport name is still not indicated in the modal title.
i5: After successfully importing, trying to add a new elementary stream, I can still add another MPEG-2 type. 


i1: 
image

i2: 
image

i3: 
image

i4: 
image

i5: 
image

**Comment by chriscodev** [comment]
hi @darlp5589 , 

update my commit branch with latest changes:

here are the updates:

- on commit successfullsubmit with ac3 elemStream [DONE]
- if ac3 elemeantary exist on import then add default data on ac3 elemetary stream [ongoing]


i1: Still the comparison isn't implemented. [DONE]

i2: I still can import the same file twice with same transport name. [cant replicate]

i3: i3: After successfully importing a transport, the checkmark beside TSID is still in black (not consistent with Java App and the checkmark beside name field). Am I safe to assume that this is fine? [DONE]

i4: Transport name is still not indicated in the modal title. [DONE]

i5: After successfully importing, trying to add a new elementary stream, I can still add another MPEG-2 type. [cant replicate]

see vids on my end
I2
https://www.veed.io/view/79f33dba-5b67-40b0-bbc2-3099fd6b204b?sharingWidget=true

i5
https://www.veed.io/view/023527d4-7822-4ebc-b2ad-fc756664bb01?sharingWidget=true

You may now review in your end.

Thanks :D

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking fixes. 

i1: Java App and Angular App error message on files imported twice isn't consistent
i2: Shouldn't this be "Success on Importing Data"?

i1: 
image

i2: 
image

**Review by darlp5589 — APPROVED** [review]
This is approved!

**Comment by triveni-codev** [comment]
Tian @chriscodev ,

1. Kindly apply the review comments that was indicated in https://github.com/triveni-codev/GBWebApp-dev/pull/478#issuecomment-1286199502 to here.
2. modal-transport-add-edit-program.component.ts: Update the spacing coding convention of the logical operator in line 378
3. Tidy up console logs from pushed changes. Keep things minimalist and artisan in the end. If you prefer, you can make changes easily by pressing dot(.) in this page.
4. Can these methods be removed?
a) addCSVtoTable()
b) checkOneTransType() 
5. Typo found on this method name: openMModalImportCSV()

**Comment by chriscodev** [comment]
hi @triveni-codev ,

new Updates Commit:


1) Kindly apply a coding convention update to your btnExportTransport(rowData) method. Can be on your final import PR since this has a PR link towards it. 
Regarding
a) spacing in conditional if-else blocks  **[done]**
b) spacing in comparison and logical operators  **[done]**
c) Checking-related console logs that could be removed  **[done]**
d) Single zone mini lintings **[done]**

2) Kindly assess & break down the flow inside btnExportTransport(rowData) method to individually-dedicated mini functions (each mini function containing one dedicated purpose/task) for abstraction. Can be on your final import PR since this has a PR link towards it.  **[done]**

1. Kindly apply the review comments that was indicated in https://github.com/triveni-codev/GBWebApp-dev/pull/478#issuecomment-1286199502 to here. [ done ]

2. modal-transport-add-edit-program.component.ts: Update the spacing coding convention of the logical operator in line 378 **[done]**
3. Tidy up console logs from pushed changes. Keep things minimalist and artisan in the end. If you prefer, you can make changes easily by pressing dot(.) in this page.
4. Can these methods be removed? **[done]**
a) addCSVtoTable() **[done]**
b) checkOneTransType()  **[done]**
5. Typo found on this method name: openMModalImportCSV() **[done]**

**Pull request merged**
