### PR TITLE
implemented adding and updating the channel extensions for atsc3 netw…

### PR DESCRIPTION
**Pull request by darlp5589**
Hi @chriscodev , @triveni-codev 

Kindly check this PR. See ticket here: https://app.asana.com/0/1201943683850147/1202710413029911

Basically just test only on adding and updating dirty change for ATSC 3 Channel Extensions. I just reused the descriptor implementation though.

Please don't test the big commit and any values from server as I haven't prepared them yet. I will be implementing them in the next set of push commit.

### CODE REVIEW

**Comment by chriscodev** [comment]
hi @darlp5589 ,

below are my comments on the PR


QA1 - on add atsc channel 1tsc3
    i input name then time zone then added channel extension
    then last i link a transport, when linking transport the channel table is gone

qa2
    - on add signaling
    add url validator icon same in client app

qa3
    - on click outside modal box, the modal closes, it should not close, only triggers when cancel or x icon is clicked

====

qa1
qa2
qa3

**Comment by chriscodev** [comment]
hi @darlp5589 ,

Here are my new findings on the latest commit:

qa1 
    on edit networks with link transport data
        - it should not have data on transport since it is used on other network type data

qa2
     on edit networks with link transport data
        - on client app it has the data on transport link, on the web app it does not retrieve the transport link data
==================

qa1 
qa1

qa2
qa2

Cheers,
Christian

**Comment by chriscodev** [comment]
hi @darlp5589 , 

below is the current findings on the lastest commit:

qa1
on edit server data
    - atsc channels no content on click update
    but for other data Row it is displaying a content

    - unlinking the transport then commiting then click update
    gives this result

================

qa1
qa1


Cheers,
Christian

**Comment by chriscodev** [comment]
hi @darlp5589 , LGTM

**Review by chriscodev — COMMENTED** [review]
LGTM

**Comment by triveni-codev** [comment]
~~~~
Commencing merge to master branch as results stated above.
PR by Darl
Main reviewer conducted by Christian
Kickstart of ATSC3 extensions development down to big commit operability - Channel extensions
https://app.asana.com/0/1201468220173184/1202710413029911/f

**Pull request merged**
