### PR TITLE
Darlp networks 1203010619466460

### PR DESCRIPTION
**Pull request by darlp5589**
Hi @.triveni-codev, @.chriscodev , @.pauljustinhernandez

ASANA: https://app.asana.com/0/1201943683850147/1203010619466460

Kindly check on this PR for ATSC 3 type service based on following details:
-you may test add and update features both for dirty change and from server data
-don't test the major-minor logics first
-don't test the big commit part yet
-don't test the Linked Transport, IP Stream and Recovery parts yet

### CODE REVIEW

**Comment by chriscodev** [comment]
hi @darlp5589 , 

here are my review on the PR, other concerns are working, here are my feedback

- 	qa1

	on server data with existing atsc channel
		when i try to add another atsc channel, then update the newly added atsc channel 
		cant proceed to updating data

- 	qa2
	on server data with existing atsc channel
		when i try to add another atsc service then try to update the major-minor using highlights
			i cant edit the field
			
qa1
qa2

**Comment by darlp5589** [comment]
Done fixing qa1 concern. Per convo, qa2 is considered to be fine for now as long as the logic behind major-minor number is intact on all types.

**Review by chriscodev — APPROVED** [review]
LGTM

**Comment by triveni-codev** [comment]
Noted on the approval.

**Comment by triveni-codev** [comment]
Temporarily closing this PR.
WIll be reopened once Recovery Settings (together with IP Stream) linking development resumes.
Blocking factor: https://app.asana.com/0/1200833614787143/1203382782335017/f

**Comment by triveni-codev** [comment]
Temporarily closing this PR.
WIll be reopened once Recovery Settings (together with IP Stream) linking development resumes.
Blocking factor: https://app.asana.com/0/1200833614787143/1203382782335017/f

**Pull request closed without merging**
