### PR TITLE
chrisdev_transport_1202187061972891

### PR DESCRIPTION
**Pull request by chriscodev**
Transports Section Development: Mapping and display of retrieved Service Group values

### CODE REVIEW

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Hi @chriscodev ,

API returned values are being pulled and reflected however, I noticed some inconsistencies that needs fixes/changes upon comparing both the web app and the actual client app.

In the image below, statmux wasn't set in the web app but is set in the client app and passed from api returned value (see other image for reference).

Also, I noticed that IP Streams data table contains a record but not being passed or empty in API return.  

image

image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Since the update is made only on the Edit AEA and ESG Settings button, below are my concerns:

-based from the image below, please also include both the FTP username and password being returned from API just like in the Client App for AEA Settings
-based from the other image below, please include "hours behind" value being returned from API for ESG Settings
-also if you noticed the api return for password, it's in plain text, I'm not sure if that is something we can do on the API side but maybe we can encrypt it for security purposes if it's necessary.



image

image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Here are my review comments:

1. From the image1 below, you can see that the password in AEA Settings is not in input type="password"
2. From the image1 below, whenever we retrieve a data from the API that has Enabled AEAT = true, the input fields should be enabled. On this case, they are disabled.
3. Fix type in modal title "Edit AEA Settinhgs" in image1. This also applies in Edit ESG Settings modal title.
4. Closing or cancelling AEA Settings modal will go back to list of service groups modal instead of the update service group modal
5. In image2, it should say "Edit Service Group - (service group name)"
6. In image3, LLS settings is passed from server but not reflected in web app yet
7. In image4, if you click Edit Broadband Settings, that modal will show but the modal title  should be "Edit Broadband Settings"
8. In image4 - Under Edit Broadband Settings: From the server, both Primary and Backup Publishing are enabled but their corresponding input fields are disabled.
9. Edit Recovery Settings button isn't working

image1:
image

image2: 
image


image3: 
image


image4:  
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Everything is already in placed except for 2 pending items:

-Edit Recovery Settings button 
-IP Streams not reflected yet

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Checked on the particular changes based on the recent PR commit messages, I can see that the changes are already in placed for the big commit as preparation for server request however, I noticed that upon clicking back the update button of that modified transport, the modified fields are reverted to their original values. This applies to the service group values as well as the LLS Settings values. This test is only limited to an existing transport being updated (not the newly added transport / dirty change) based on our convo.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Here are my concerns:

1. Updating the group id will not reflect after visiting back the service group modal. It reflects in client app.
2. Disabling the DSTP and Statmux checkbox will reset the values. They are retained in client app.
3. In image1, destination address in ESG settings will set a checkmark even if address is not valid. 
4. In image2, Edit Broadband and Edit AEA Settings won't let me proceed. It gets stuck and the modal isn't clickable anymore.

image1: 
image

image2:
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Based on convo, I should check only the recent concerns/feedbacks I raised and considering that Edit Broadband and Edit AEA Settings are not in placed yet, we only have 1 pending concern below.

-destination address in ESG settings will set a checkmark even if address is not valid

Edit:  Per convo, IP address concerns will be put in a separate ticket thus I considered this PR as approved except that we have pending concerns not in placed yet but I will still have to specify them here so we can revisit them in the future as reminders. See below:

Pending items:
-Edit Recovery Settings button not working yet
-IP Streams not reflected yet
-Editing Broadband and AEA Settings won't let me proceed after clicking OK button. It gets stuck and the modal isn't clickable anymore.

**Comment by triveni-codev** [comment]
Confirmed for the most part, requirement-wise and implementation-wise. However, I have further concerns and review comments that I will raise in a different avenue. Merging this to master.


~~~~~~~~~~~
Ticket scopes:
1. Transports Section Development: Mapping and display of retrieved Service Group values
https://app.asana.com/0/1201468220173184/1202187061972891/f
2. Transports Section Development: Data mapping and UI design for "Edit LLS Settings" Panel interaction
https://app.asana.com/0/1202172889691467/1202187061972899/f
3. Continuous development of scenario #6 for LLS Settings
https://app.asana.com/0/0/1202249852885588/f
4. [Bug] Transports Section: Programs List table data is empty when updating an existing ATSC-Cable/Terrestrial Transport
https://app.asana.com/0/1202172889691467/1202210153506888/f
5. Transports Section Development: Data mapping and UI design for "Edit Broadband Settings" Panel interaction
https://app.asana.com/0/1202172889691467/1202210153506872/f
6. Transports Section Development: Data mapping and UI design for "Edit ESG Settings" Panel interaction
https://app.asana.com/0/1202172889691467/1202210153506880/f
7. Transports Section Development: Data mapping and UI design for "Edit AEA Settings" Panel interaction
https://app.asana.com/0/1201468220173184/1202210153506896/f
8. Transports Section - ATSC3 type development: Update Transport functionality & LLS Panel Dirty change detection
https://app.asana.com/0/1201468220173184/1202249852885641/f

**Pull request merged**
