### PR TITLE
Justin_AlarmSection-AlarmNotifCounter_1202417486432196

### PR DESCRIPTION
**Pull request by pauljustinhernandez**
ASANA ticket: https://app.asana.com/0/1202364707885489/1202554243117968/f

- Already implemented Angular Akita State Management (lower version)
- Already setup all the necessary configurations, states, services, query, and store.
- The main setup is reusable and easy to implement.
- SET and GET of Alarm notif counter were already established on the state management and working as intended.

### CODE REVIEW

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Hi Jus, done checking your PR along with parallel testing using GB Client App. 

Here are my concerns:
1. image1: By default, I have no existing Outputs in Client App but the notification count has 9 already and it shows all my channels that are not linked being set as "CHANNEL_UNLINKED" in the type column. Is this part of the notification counter scope? 
2. When I removed all transports in Client App as well then clicked commit, the notification counter is still there. I checked postman using the API request URL and it indeed fires those 9 records. Probably another feature to look up soon as part of Dave's other scenario for alarm. 
3. image2: I was able to successfully remove the notification counter by clearing all transports, networks and outputs then added a transport and associated it with an output. Now that I removed the associated transport of a given output, it fires the counter already which is correct. However, when deleted that output and clicked commit, the counter is still there with the log. It will only be removed once we click anywhere in the web app that will redirect to a different url (needs real-time update).
4. image3: can you confirm that the notification counter is only applicable for outputs w/o tranports and should be Online? Offline one isn't included.
5. image4: in relation to image3, I set the offline output (still w/o transport) to online then commit and it is already incrementing the counter to 2. However, when I set it to offline again then commit, the counter isn't decrementing but will only decrement if we click any where in web app that redirects to other url (needs real-time update). 
6. image5: I have 3 outputs and first 2 of them are not associated with a trasnport thus the counter in the web app is 2 which is correct. However, when I go to transports menu and remove that transport being associated on the 3rd output then commit and went back to outputs menu, you can see that the 3rd output has no associated transport already but in the client app, it's still counter = 2 when it should be 3. Take note, this won't reflect even if we click anywhere in the web app that will redirect to other url.
7. image6: ultimately, as a universal impression of a bell icon which is a notification on most sites, wouldn't it be weird that we get notified on something then clicked that notification and still the counter is there even if already seen it? I mean wouldn't a different icon be better for this alarm instead of a bell? Hehe! just a little concern.

image1:
image

image2: 
image

image3: 
image

image4:
image

image5: 
image

image6: 
image

**Comment by pauljustinhernandez** [comment]
Hi Darl, below are my answers to your concerns;

1.) Yes Darl, I can confirm that this is part of the notification counter scope, as CHANNEL_UNLINKED is a type of alarm. Maybe you have an unlinked channel data in your client app. For you to confirm this, I suggest that you should clear your channel data? or maybe clear your entire DB if that would be fine on your part.
2.) Very nice discovery Darl! Seconded. This should be discussed with Dave, if this is an issue on their part, or this is actually they implemented it. Please support me on this Darl.
3.) Upon checking this scenario, I can confirm this issue and this should be discussed with Dave. See this loom clip for our reference - https://www.loom.com/share/5419c78e8fa249eca88731d116aca8ce
4.) I can confirm this Darl, All outputs should be enabled, as alarm stomp channel will not detect it if they are disabled.
5.) Agree with this. Both disabling and enabling an output should trigger the alarm stomp channel upon commit. See this loom clip for our reference - https://www.loom.com/share/ff4d7395e66c48b7bf35fe469fe12ade
6.) Upon checking this scenario, Both of our investigation Darl didn't matched, but rather I discovered a weird issue regarding this one. See this loom clip for our reference -   https://www.loom.com/share/52b66d6fb94645719b582fa4de9ed2af
7.) Agree with your input on this Darl, Let's discuss it with Jan on our DSU. Thanks for this.

Btw, regarding this:
``` It will only be removed once we click anywhere in the web app that will redirect to a different url (needs real-time update).```
This is not connected with the issues you have encountered, but rather a bug on my end (FE) as it should not be calling again the /activeAlarms endpoint everytime the user navigates on any page. I will be pushing a new commit on this.

cc: @darlp5589 @

**Review by darlp5589 — APPROVED** [review]
Upon checking and based on the videos and set of explanations, we have agreed to consider the logs as good since these are something to work on their end and everything on the web app is already prepared which means once they fixed the firing of event, our app will automatic receive it and reflect the action.

**Comment by triveni-codev** [comment]
Sorted out code conflict found in header component - nav-item class.
BE dependency concerns have been conveyed to Dave in the meeting.

~~~~~
Fundamental alarm counter implementation
https://app.asana.com/0/1202364707885489/1202554243117968/f

**Comment by triveni-codev** [comment]
Confirmed by the main reviewer w/ the following notes: https://github.com/triveni-codev/GBWebApp-dev/pull/446#pullrequestreview-1038550603

Furthermore, closing discussions and clarifications on the implementation were discussed in our call. 

A PR before this PR has been sorted out and will now commence on this. (Not that there was a dependency but only for good measure as there were shared file changes). 


~~~~
Fundamental alarm counter implementation
https://app.asana.com/0/1202364707885489/1202554243117968/f

**Pull request merged**
