### PR TITLE
Darlp networks service extension 1203671430631939

### PR DESCRIPTION
**Pull request by darlp5589**
Hi @triveni-codev ,

Kindly have someone to check this PR for ATSC 3 Service Extensions.

ASANA: https://app.asana.com/0/1201943683850147/1203671430631939

Considerations:
-this is limited only for atsc 3 types
-this is limited only for the first 3 service extension types (capabilities, drm system id and global service id)

To Test:
-adding and updating of atsc 3 service extensions on dirty change
-can retrieve any of these 3 existing service extension types from server, display and can be updated
-logics for the specified first 3 service extensions 
    >should allow any character inputs
    >should only have one instance (i.e if capabilities is selected, it shouldn't be available in the dropdown options) even on existing record from server

Do Not Test: Big Commit Add and Update

### CODE REVIEW

**Comment by pauljustinhernandez** [comment]
Hi Darl @darlp5589 , dropping here an initial PR concern;

- Upon update, original data should be retrieved again after cancelling the amends
cancel_data

**Comment by darlp5589** [comment]
@pauljustinhernandez you may now pull the fix I just pushed for this concern. Thanks!

**Comment by pauljustinhernandez** [comment]
Hi Darl @darlp5589 , dropping a minor issue here.

- '**EDIT**' btn should be '**UPDATE**' btn
edit btn

**Comment by pauljustinhernandez** [comment]
Done testing service extensions - CRUD, both on dirty change and clientapp.
LGTM! except for the minor issue I have raised above.

Also, the ff. are not included in the test cases I have tested:
- CANCEL part of the service extensions
- BIG COMMIT
- Other service extensions types

**Comment by darlp5589** [comment]
@pauljustinhernandez ,

Fixed. I'll be working on Big Commit. Keep you posted. Thanks!

**Comment by pauljustinhernandez** [comment]
Hi Darl @darlp5589 , dropping here another concern

- Bug encountered upon updating service extensions
cancel

**Comment by darlp5589** [comment]
@pauljustinhernandez you may now verify my fixes on your update concern. Please also include testing the Big Commit for Updating Service Extensions. Thanks!

**Comment by pauljustinhernandez** [comment]
Hi Darl @darlp5589 , dropping here another concern

- Service extension should be selected again after deleting it
dropdown

**Comment by darlp5589** [comment]
@pauljustinhernandez , I haven't implemented any delete feature on my entire Network tasks yet.

**Comment by pauljustinhernandez** [comment]
LGTM Darl! @darlp5589 

cc: @triveni-codev

**Pull request merged**
