### PR TITLE
Justin_Revamp-dashboard-pages-folder_1203212360956569_restructured

### PR DESCRIPTION
**Pull request by pauljustinhernandez**
ASANA ticket: https://app.asana.com/0/1203173080108752/1203212360956569/f

**Description**: Initial revamp of "pages/dashboard" folder
- Renamed dashboard folder into main via `rename-angular` extension library
- Renamed dashboard services, models and other utilities into main
- Initial regression testing conducted

**Note**: This is a restructured PR of https://github.com/triveni-codev/GBWebApp-dev/pull/488 . As discussed by the team, we need re-create the amends regarding this to avoid merging errors.
~~ Reference: https://app.asana.com/0/0/1203212360956569/1203318703397637/f

cc: @triveni-codev

### CODE REVIEW

**Comment by darlp5589** [comment]
Will check.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking PR. All my previous revamp concerns were good except that I found a new concern and I believe this is not something caused by the revamp but a concern probably overlooked on the previous PR checking.

1. i1: Tried to add an output then linked to a transport clicked prev then clicked next, that shows up. The linked transport is there but the button shouldn't enabled the add but the remove and view.

i1: 
image

**Comment by triveni-codev** [comment]
All reviews and notes confirmed. The lone outlier issue pointed out during review process will be fixed well and good separately.
I'll proceed in making SVN adjustments afterwards as SVN is much less graceful to this kind of revamp.

**Review by triveni-codev — COMMENTED** [review]
Added post-labeling measures tracking for myself

These are the actual file/file path changes where dashboard is explicitly changed to main
1. src/app/_models/dashboard.ts → src/app/_models/main.ts
2. /activity-log/activity-log.component.html → .../activity-log/activity-log.component.html
3. src/app/pages/main/activity-log/activity-log.component.html
4. src/app/pages/main/activity-log/activity-log.component.scss
5. src/app/pages/main/activity-log/activity-log.component.spec.ts
6. src/app/pages/main/activity-log/activity-log.component.ts
7. src/app/pages/main/alarm/active-alarms/active-alarms.component.html
8. src/app/pages/main/alarm/active-alarms/active-alarms.component.scss
9. src/app/pages/main/alarm/active-alarms/active-alarms.component.spec.ts
10. src/app/pages/main/alarm/active-alarms/active-alarms.component.ts
11. src/app/pages/main/alarm/alarm.component.html
12. src/app/pages/main/alarm/alarm.component.scss
13. src/app/pages/main/alarm/alarm.component.spec.ts
14. src/app/pages/main/alarm/alarm.component.ts
15. src/app/pages/main/alarm/alarm.module.ts
16. src/app/pages/main/alarm/configuration/configuration.component.html
17. src/app/pages/main/alarm/configuration/configuration.component.scss
18. src/app/pages/main/alarm/configuration/configuration.component.spec.ts
19. src/app/pages/main/alarm/configuration/configuration.component.ts
20. src/app/pages/main/alarm/history/history.component.html
21. src/app/pages/main/alarm/history/history.component.scss
22. src/app/pages/main/alarm/history/history.component.spec.ts
23. src/app/pages/main/alarm/history/history.component.ts
24. src/app/pages/main/certificate-request/certificate-request.component.html
25. src/app/pages/main/certificate-request/certificate-request.component.scss
26. src/app/pages/main/certificate-request/certificate-request.component.spec.ts
27. src/app/pages/main/certificate-request/certificate-request.component.ts
28. src/app/pages/main/dev-component/dev-component.component.html
29. src/app/pages/main/dev-component/dev-component.component.scss
30. src/app/pages/main/dev-component/dev-component.component.spec.ts
31. src/app/pages/main/dev-component/dev-component.component.ts
32. src/app/pages/main/features/features.component.html
33. src/app/pages/main/features/features.component.scss
34. src/app/pages/main/features/features.component.spec.ts
35. src/app/pages/main/features/features.component.ts
36. src/app/pages/main/home/home.component.html
37. src/app/pages/main/home/home.component.scss
38. src/app/pages/main/home/home.component.spec.ts
39. src/app/pages/main/home/home.component.ts
40. src/app/pages/main/main-routing.module.ts
41. src/app/pages/main/main.component.html
42. src/app/pages/main/main.component.scss
43. src/app/pages/main/main.component.spec.ts
44. src/app/pages/main/main.component.ts
45. src/app/pages/main/main.module.ts
46. src/app/pages/main/network-config/network-config.component.html
47. src/app/pages/main/network-config/network-config.component.scss
48. src/app/pages/main/network-config/network-config.component.spec.ts
49. src/app/pages/main/network-config/network-config.component.ts
50. src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-channel/modal-networks-atsc-channel.component.html
51. src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-channel/modal-networks-atsc-channel.component.scss
52. src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-channel/modal-networks-atsc-channel.component.spec.ts
53. src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-channel/modal-networks-atsc-channel.component.ts
54. src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-network/modal-networks-atsc-network.component.html
55. src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-network/modal-networks-atsc-network.component.scss
56. src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-network/modal-networks-atsc-network.component.spec.ts
57. src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-network/modal-networks-atsc-network.component.ts
58. src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.html
59. src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.scss
60. src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.spec.ts
61. src/app/pages/main/network-config/networks/modal-networks/modal-networks-atsc-service/modal-networks-atsc-service.component.ts
62. src/app/pages/main/network-config/networks/modal-networks/modal-networks-caption/modal-networks-caption.component.html
63. src/app/pages/main/network-config/networks/modal-networks/modal-networks-caption/modal-networks-caption.component.scss
64. src/app/pages/main/network-config/networks/modal-networks/modal-networks-caption/modal-networks-caption.component.spec.ts
65. src/app/pages/main/network-config/networks/modal-networks/modal-networks-caption/modal-networks-caption.component.ts
66. src/app/pages/main/network-config/networks/modal-networks/modal-networks-descriptor/modal-networks-descriptor.component.html
67. src/app/pages/main/network-config/networks/modal-networks/modal-networks-descriptor/modal-networks-descriptor.component.scss
68. src/app/pages/main/network-config/networks/modal-networks/modal-networks-descriptor/modal-networks-descriptor.component.spec.ts
69. src/app/pages/main/network-config/networks/modal-networks/modal-networks-descriptor/modal-networks-descriptor.component.ts
70. src/app/pages/main/network-config/networks/modal-networks/modal-networks-schedule/modal-networks-schedule.component.html
71. src/app/pages/main/network-config/networks/modal-networks/modal-networks-schedule/modal-networks-schedule.component.scss
72. src/app/pages/main/network-config/networks/modal-networks/modal-networks-schedule/modal-networks-schedule.component.spec.ts
73. src/app/pages/main/network-config/networks/modal-networks/modal-networks-schedule/modal-networks-schedule.component.ts
74. src/app/pages/main/network-config/networks/modal-networks/modal-networks-transport-link-program/modal-networks-transport-link-program.component.html
75. src/app/pages/main/network-config/networks/modal-networks/modal-networks-transport-link-program/modal-networks-transport-link-program.component.scss
76. src/app/pages/main/network-config/networks/modal-networks/modal-networks-transport-link-program/modal-networks-transport-link-program.component.spec.ts
77. src/app/pages/main/network-config/networks/modal-networks/modal-networks-transport-link-program/modal-networks-transport-link-program.component.ts
78. src/app/pages/main/network-config/networks/networks.component.html
79. src/app/pages/main/network-config/networks/networks.component.scss
80. src/app/pages/main/network-config/networks/networks.component.spec.ts
81. src/app/pages/main/network-config/networks/networks.component.ts
82. src/app/pages/main/network-config/output/modal-outputs-atsc3-udp/modal-outputs-atsc3-udp.component.html
83. src/app/pages/main/network-config/output/modal-outputs-atsc3-udp/modal-outputs-atsc3-udp.component.scss
84. src/app/pages/main/network-config/output/modal-outputs-atsc3-udp/modal-outputs-atsc3-udp.component.spec.ts
85. src/app/pages/main/network-config/output/modal-outputs-atsc3-udp/modal-outputs-atsc3-udp.component.ts
86. src/app/pages/main/network-config/output/modal-outputs-ericsson-avp/modal-outputs-ericsson-avp.component.html
87. src/app/pages/main/network-config/output/modal-outputs-ericsson-avp/modal-outputs-ericsson-avp.component.scss
88. src/app/pages/main/network-config/output/modal-outputs-ericsson-avp/modal-outputs-ericsson-avp.component.spec.ts
89. src/app/pages/main/network-config/output/modal-outputs-ericsson-avp/modal-outputs-ericsson-avp.component.ts
90. src/app/pages/main/network-config/output/modal-outputs-ericsson-mx5600/modal-outputs-ericsson-mx5600.component.html
91. src/app/pages/main/network-config/output/modal-outputs-ericsson-mx5600/modal-outputs-ericsson-mx5600.component.scss
92. src/app/pages/main/network-config/output/modal-outputs-ericsson-mx5600/modal-outputs-ericsson-mx5600.component.spec.ts
93. src/app/pages/main/network-config/output/modal-outputs-ericsson-mx5600/modal-outputs-ericsson-mx5600.component.ts
94. src/app/pages/main/network-config/output/modal-outputs-ericsson-mx8400/modal-outputs-ericsson-mx8400.component.html
95. src/app/pages/main/network-config/output/modal-outputs-ericsson-mx8400/modal-outputs-ericsson-mx8400.component.scss
96. src/app/pages/main/network-config/output/modal-outputs-ericsson-mx8400/modal-outputs-ericsson-mx8400.component.spec.ts
97. src/app/pages/main/network-config/output/modal-outputs-ericsson-mx8400/modal-outputs-ericsson-mx8400.component.ts
98. src/app/pages/main/network-config/output/modal-outputs-select-transports/modal-outputs-select-transports.component.html
99. src/app/pages/main/network-config/output/modal-outputs-select-transports/modal-outputs-select-transports.component.scss
100. src/app/pages/main/network-config/output/modal-outputs-select-transports/modal-outputs-select-transports.component.spec.ts
101. src/app/pages/main/network-config/output/modal-outputs-select-transports/modal-outputs-select-transports.component.ts
102. src/app/pages/main/network-config/output/modal-outputs-test-connection/modal-outputs-test-connection.component.html
103. src/app/pages/main/network-config/output/modal-outputs-test-connection/modal-outputs-test-connection.component.scss
104. src/app/pages/main/network-config/output/modal-outputs-test-connection/modal-outputs-test-connection.component.spec.ts
105. src/app/pages/main/network-config/output/modal-outputs-test-connection/modal-outputs-test-connection.component.ts
106. src/app/pages/main/network-config/output/modal-outputs-thomson-netprocessor/modal-outputs-thomson-netprocessor.component.html
107. src/app/pages/main/network-config/output/modal-outputs-thomson-netprocessor/modal-outputs-thomson-netprocessor.component.scss
108. src/app/pages/main/network-config/output/modal-outputs-thomson-netprocessor/modal-outputs-thomson-netprocessor.component.spec.ts
109. src/app/pages/main/network-config/output/modal-outputs-thomson-netprocessor/modal-outputs-thomson-netprocessor.component.ts
110. src/app/pages/main/network-config/output/modal-outputs-triveni-carousel/modal-outputs-triveni-carousel.component.html
111. src/app/pages/main/network-config/output/modal-outputs-triveni-carousel/modal-outputs-triveni-carousel.component.scss
112. src/app/pages/main/network-config/output/modal-outputs-triveni-carousel/modal-outputs-triveni-carousel.component.spec.ts
113. src/app/pages/main/network-config/output/modal-outputs-triveni-carousel/modal-outputs-triveni-carousel.component.ts
114. src/app/pages/main/network-config/output/output.component.html
115. src/app/pages/main/network-config/output/output.component.scss
116. src/app/pages/main/network-config/output/output.component.spec.ts
117. src/app/pages/main/network-config/output/output.component.ts
118. src/app/pages/main/network-config/schedule-provider/modal-sp-add-schedule/modal-sp-add-schedule.component.html
119. src/app/pages/main/network-config/schedule-provider/modal-sp-add-schedule/modal-sp-add-schedule.component.scss
120. src/app/pages/main/network-config/schedule-provider/modal-sp-add-schedule/modal-sp-add-schedule.component.spec.ts
121. src/app/pages/main/network-config/schedule-provider/modal-sp-add-schedule/modal-sp-add-schedule.component.ts
122. src/app/pages/main/network-config/schedule-provider/modal-sp-onconnect/modal-sp-onconnect.component.html
123. src/app/pages/main/network-config/schedule-provider/modal-sp-onconnect/modal-sp-onconnect.component.scss
124. src/app/pages/main/network-config/schedule-provider/modal-sp-onconnect/modal-sp-onconnect.component.spec.ts
125. src/app/pages/main/network-config/schedule-provider/modal-sp-onconnect/modal-sp-onconnect.component.ts
126. src/app/pages/main/network-config/schedule-provider/modal-sp-pmcp/modal-sp-pmcp.component.html
127. src/app/pages/main/network-config/schedule-provider/modal-sp-pmcp/modal-sp-pmcp.component.scss
128. src/app/pages/main/network-config/schedule-provider/modal-sp-pmcp/modal-sp-pmcp.component.spec.ts
129. src/app/pages/main/network-config/schedule-provider/modal-sp-pmcp/modal-sp-pmcp.component.ts
130. src/app/pages/main/network-config/schedule-provider/modal-sp-rovi/modal-sp-rovi.component.html
131. src/app/pages/main/network-config/schedule-provider/modal-sp-rovi/modal-sp-rovi.component.scss
132. src/app/pages/main/network-config/schedule-provider/modal-sp-rovi/modal-sp-rovi.component.spec.ts
133. src/app/pages/main/network-config/schedule-provider/modal-sp-rovi/modal-sp-rovi.component.ts
134. src/app/pages/main/network-config/schedule-provider/modal-sp-selectxslt/modal-sp-selectxslt.component.html
135. src/app/pages/main/network-config/schedule-provider/modal-sp-selectxslt/modal-sp-selectxslt.component.scss
136. src/app/pages/main/network-config/schedule-provider/modal-sp-selectxslt/modal-sp-selectxslt.component.spec.ts
137. src/app/pages/main/network-config/schedule-provider/modal-sp-selectxslt/modal-sp-selectxslt.component.ts
138. src/app/pages/main/network-config/schedule-provider/modal-sp-testconnection/modal-sp-testconnection.component.html
139. src/app/pages/main/network-config/schedule-provider/modal-sp-testconnection/modal-sp-testconnection.component.scss
140. src/app/pages/main/network-config/schedule-provider/modal-sp-testconnection/modal-sp-testconnection.component.spec.ts
141. src/app/pages/main/network-config/schedule-provider/modal-sp-testconnection/modal-sp-testconnection.component.ts
142. src/app/pages/main/network-config/schedule-provider/modal-sp-viewsched/modal-sp-viewsched.component.html
143. src/app/pages/main/network-config/schedule-provider/modal-sp-viewsched/modal-sp-viewsched.component.scss
144. src/app/pages/main/network-config/schedule-provider/modal-sp-viewsched/modal-sp-viewsched.component.spec.ts
145. src/app/pages/main/network-config/schedule-provider/modal-sp-viewsched/modal-sp-viewsched.component.ts
146. src/app/pages/main/network-config/schedule-provider/schedule-provider.component.html
147. src/app/pages/main/network-config/schedule-provider/schedule-provider.component.scss
148. src/app/pages/main/network-config/schedule-provider/schedule-provider.component.spec.ts
149. src/app/pages/main/network-config/schedule-provider/schedule-provider.component.ts
150. src/app/pages/main/network-config/transport/transport.component.html
151. src/app/pages/main/network-config/transport/transport.component.scss
152. src/app/pages/main/network-config/transport/transport.component.spec.ts
153. src/app/pages/main/network-config/transport/transport.component.ts
154. src/app/pages/main/networking/networking.component.html
155. src/app/pages/main/networking/networking.component.scss
156. src/app/pages/main/networking/networking.component.spec.ts
157. src/app/pages/main/networking/networking.component.ts
158. src/app/pages/main/networks/networks.component.html
159. src/app/pages/main/networks/networks.component.scss
160. src/app/pages/main/networks/networks.component.spec.ts
161. src/app/pages/main/networks/networks.component.ts
162. src/app/pages/main/smtp-email/smtp-email.component.html
163. src/app/pages/main/smtp-email/smtp-email.component.scss
164. src/app/pages/main/smtp-email/smtp-email.component.spec.ts
165. src/app/pages/main/smtp-email/smtp-email.component.ts
166. src/app/pages/main/snmp/snmp.component.html
167. src/app/pages/main/snmp/snmp.component.scss
168. src/app/pages/main/snmp/snmp.component.spec.ts
169. src/app/pages/main/snmp/snmp.component.ts
170. src/app/pages/main/sw-update/sw-update.component.html
171. src/app/pages/main/sw-update/sw-update.component.scss
172. src/app/pages/main/sw-update/sw-update.component.spec.ts
173. src/app/pages/main/sw-update/sw-update.component.ts
174. src/app/pages/main/system-health/system-health.component.html
175. src/app/pages/main/system-health/system-health.component.scss
176. src/app/pages/main/system-health/system-health.component.spec.ts
177. src/app/pages/main/system-health/system-health.component.ts
178. src/app/pages/main/users/users.component.html
179. src/app/pages/main/users/users.component.scss
180. src/app/pages/main/users/users.component.spec.ts
181. src/app/pages/main/users/users.component.ts
182. src/app/services/main.service.ts

**Pull request merged**
