### PR TITLE
chrisdev_transportSection_1202573310671261

### PR DESCRIPTION
**Pull request by chriscodev**
ASANA TICKET: https://app.asana.com/0/1202601797867653/1202573310671261

ticket: only add functionality and  added new code structures to be same with service groups

no update and add-edit functionality just merely getting data and retrieving to parent ui

### CODE REVIEW

**Comment by chriscodev** [comment]
hi @darlp5589  @triveni-codev ,

just an update on this ticket:

PSIP can add programs
PSIP can edit programs
PSIP can add edit programs
PSIP can retrieve program data
PSIP can commit added edit program data

ongoing on adding elementary stream

Cheers,
Christian

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done with my review along with GB ClientApp comparison. Here are my concerns:

1. image1: based from the client app, number is incrementing based on the number of programs in the list. So if we have 2 existing programs in the list, the next time we add a new program, the default value of number will be 3.
2. image2: not sure if this is big deal but in the client app, it's capital 'CA'.
3. image3: in client app, you can't have 2 same number values
4. image4: updating a program from the list then merely appending any value of the existing number, that shows up.
5. in relation to image4, once that issue showed up, I clicked X or cancel, it goes back to the program list w/o changing the original value but when I updated again, it preserves the draft/unfinished edit with the issue.
6. image5: after successfully adding a new psip terrestrial transport with a program in the list, editing just the name of that newly added transport will not reflect in the list. It remains trans2 instead of already updated to trans2a.
7. image6: I was able to commit my newly added transport with a program in the list and retrieved it. When I updated that transport and updated that program then added another program, that newly added program overwrites the existing program on the list.


image1: 
image

image2: 
image

image3: 
image

image4: 
image

image5: 
image

image6: 
image

**Comment by chriscodev** [comment]
hi @darlp5589 , new PR updates

**[Done]:**  image1: based from the client app, number is incrementing based on the number of programs in the list. So if we have 2 existing programs in the list, the next time we add a new program, the default value of number will be 3.

**[Done]:**  image2: not sure if this is big deal but in the client app, it's capital 'CA'.

**[Done]:**  image3: in client app, you can't have 2 same number values

**[Done]:**  image4: updating a program from the list then merely appending any value of the existing number, that shows up.

**[Done]:** in relation to image4, once that issue showed up, I clicked X or cancel, it goes back to the program list w/o changing the original value but when I updated again, it preserves the draft/unfinished edit with the issue.

**[Done]:** image5: after successfully adding a new psip terrestrial transport with a program in the list, editing just the name of that newly added transport will not reflect in the list. It remains trans2 instead of already updated to trans2a.

**[Done]:** image6: I was able to commit my newly added transport with a program in the list and retrieved it. When I updated that transport and updated that program then added another program, that newly added program overwrites the existing program on the list.

Cheers,
Christian

**Review by darlp5589 — CHANGES_REQUESTED** [review]
I have checked the fixes and found further concerns in relation to the fixes itself.

1. For the incrementing value of number, it works good already however, say for example we have 2 programs with numbers 1 and 100, the next time we add a new program, it should be 3. Currently, it's 101.
2. image1: I added a new transport with 1 and 2 number values on the list then updated the number 2 with 200 and clicked Add for that transport. When I updated that newly added transport and goes back to program list, there are already numbers 2 and 200 instead of just the updated number 200 record.
3. image2: In relation to image1 concern, after adding that new transport, when I add another transport, the default number value will be the next value of the latest program value from the other transport. So on this case it starts at 201 instead of just 1 since it's a new transport.
4. Assuming we have an existing transport with a program (number 1) from server. If we update that transport with just the name then added a new transport and program, the default value of the program will be number 2 instead of 1 (because it looks up on the previous transport's program number).


image1: 
image

image2: 
image

**Comment by chriscodev** [comment]
hi @darlp5589 , new PR commit updates :https://github.com/triveni-codev/GBWebApp-dev/pull/449/commits/1678122b6af36a852495f27b0cf4a8cf5bc8f764

**DONE** For the incrementing value of number, it works good already however, say for example we have 2 programs with numbers 1 and 100, the next time we add a new program, it should be 3. Currently, it's 101.

**DONE** image1: I added a new transport with 1 and 2 number values on the list then updated the number 2 with 200 and clicked Add for that transport. When I updated that newly added transport and goes back to program list, there are already numbers 2 and 200 instead of just the updated number 200 record.

**DONE** image2: In relation to image1 concern, after adding that new transport, when I add another transport, the default number value will be the next value of the latest program value from the other transport. So on this case it starts at 201 instead of just 1 since it's a new transport.

**DONE** Assuming we have an existing transport with a program (number 1) from server. If we update that transport with just the name then added a new transport and program, the default value of the program will be number 2 instead of 1 (because it looks up on the previous transport's program number).

Cheers,
Christian

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking. Here are my feedbacks:

1. I added a transport with just 1 program in the list. I then updated that program then clicked to add the transport. When I updated that newly added transport and go to program list, the number value of that only 1 program reverts to original value instead of the updated one.
2. image1: Added just 1 transport along with 2 existing transports from server then tried to add more transport but the add button is deactivated for some reason worth checking for. I only have 3 total transports (not 5).

image1: 
image

**Comment by chriscodev** [comment]
hi @darlp5589 , new PR updates
https://github.com/triveni-codev/GBWebApp-dev/pull/449/commits/057302320aca5c903415fc5588fbb44d5444a9ec

with regards on 
image1: Added just 1 transport along with 2 existing transports from server then tried to add more transport but the add button is deactivated for some reason worth checking for. I only have 3 total transports (not 5).
 let me know if your max transport is 3 found on features tab
Screenshot 2022-07-26 191633

Cheers,
Christian

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Here are my concerns on PR Review:

1. image1: I added a transport with a program with a number value of 100 then clicked ADD. Updating that transport and program number value of 100 to 10011, that will show up.
2. image2: I was now able to replicate the issue about having disabled ADD button even on less than 5 transports only. Try adding a transport with several programs then click ADD. It will disable the ADD button. On my case I have 1 existing transport from server then added a transport with 4 programs. It disabled the ADD button.

image1: 
image

image2: 
image

**Comment by chriscodev** [comment]
hi @darlp5589 ,

done on PR review fixes, you may now check this latest commit : https://github.com/triveni-codev/GBWebApp-dev/pull/449/commits/305a040a2dfbc9e3ddeb2a54c6035cf9a29a97ce

Done image1: I added a transport with a program with a number value of 100 then clicked ADD. Updating that transport and program number value of 100 to 10011, that will show up. 

Done image2: I was now able to replicate the issue about having disabled ADD button even on less than 5 transports only. Try adding a transport with several programs then click ADD. It will disable the ADD button. On my case I have 1 existing transport from server then added a transport with 4 programs. It disabled the ADD button.

Cheers,
Christian

**Review by darlp5589 — APPROVED** [review]
Done checking. No concerns left! 

I have approved this!

**Comment by chriscodev** [comment]
hi @triveni-codev , on this new commit ive added the elem stream updates

commit: https://github.com/triveni-codev/GBWebApp-dev/pull/449/commits/2b95e50bb405e9ab0fc7265b341e35ac476379cf

MPEG-2 (ISO/IEC 13818-2)

- success on added elementary streams to program list

- success convert transport stream type to actual streamtype code

- success convert transport stream type code to actual streamtype name

- success to commit newly added elementary stream 

ongoing EDIT MPEG-2 (ISO/IEC 13818-2)
to follow AC-3 Audio modal add and edit functionality

**Comment by triveni-codev** [comment]
New scope for review:
Elementary Streams' Big Commit and dirty change handling:
1. MPEG-2 (ISO/IEC 13818-2)
2. AC-3 Audio

image

**Comment by chriscodev** [comment]
hi @darl,

this new commit is ready for review
[chrisdev_transportSection_1202573310671261](https://github.com/triveni-codev/GBWebApp-dev/pull/449/commits/680545653a61b4350224459f1e88442316dcfc3e)

- can now add and edit elementary streams
- can  now commit elemetary  streams

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking along with GB ClientApp. Here are my review comments:

1. i1: please remove the coded value on the right if no input
2. i2: not sure if this is fine but maybe we can take off space in the input
3. i3: the gbclient app allows a 0 input. Just putting this here for further confirmation if it's fine to follow or not.
4. i4: clicking outside the modal will close the modal unlike the rest of the modals
5. i5: dropdown for type of service has unspecified and karaoke options not in the clientapp
6. i6: audio id, main service and associated service in clientApp allow a 0 inputs 
7. i7: I can only type 1 character in the description text field
8. i8: everytime you cancel or close the add ac3 elementary stream modal, it should go back directly to add program modal (not on add elementary stream modal) just like the client app.
9. i8: add elementary stream modal retains the value even if close or cancel is clicked.
10. i9: language dropdown order is different from clientapp
11. i10: clientapp uses less than or equal symbol but not in the angular app
12. i11: added mpeg-2 stream type then updated that by only appending pid value. That error shows up even if only 1 record and doesn't exist.
13. same scenario, add an mpeg-2 then update and try to edit pid value then close/cancel, updating it again will retain the unsaved draft.
14. i12: had an existing mpeg2 stream type from server and clicked update button on it then closed. Now when I attempted to add a new elementary stream, it retained on the edit modal of that newly closed edit modal for mpeg2 record.



i1: 
image

i2: 
image

i3: 
image

i4: 
image

i5: 
image

i6: 
image

i7: 
image

i8: 
image

i9: 
image

i10: 
image

i11: 
image

i12: 
image

**Comment by chriscodev** [comment]
hi @darlp5589 , @triveni-codev ,

partial updates

[DONE] - i1: please remove the coded value on the right if no input

[DONE] - i2: not sure if this is fine but maybe we can take off space in the input

[DONE] -i3: the gbclient app allows a 0 input. Just putting this here for further confirmation if it's fine to follow or not.

[DONE] - i4: clicking outside the modal will close the modal unlike the rest of the modals

[DONE] - i5: dropdown for type of service has unspecified and karaoke options not in the clientapp

[DONE] - i6: audio id, main service and associated service in clientApp allow a 0 inputs

[DONE] - i7: I can only type 1 character in the description text field

[DONE] - i8: everytime you cancel or close the add ac3 elementary stream modal, it should go back directly to add program 
modal (not on add elementary stream modal) just like the client app.

[DONE] - i8: add elementary stream modal retains the value even if close or cancel is clicked.

[DONE] - i9: language dropdown order is different from clientapp


to be created a new ticket
====================
i10: clientapp uses less than or equal symbol but not in the angular app
i11: added mpeg-2 stream type then updated that by only appending pid value. That error shows up even if only 1 record and doesn't exist.
same scenario, add an mpeg-2 then update and try to edit pid value then close/cancel, updating it again will retain the unsaved draft.
i12: had an existing mpeg2 stream type from server and clicked update button on it then closed. Now when I attempted to add a new elementary stream, it retained on the edit modal of that newly closed edit modal for mpeg2 record.

cheers,
Christian

**Comment by triveni-codev** [comment]
In connection to the above, Review comments No. 5, 10 , 11 and 12 will be placed to a branched out separately for further dedicated investigation.

Thank you,
-Jan

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done reviewing just on the fixes. Here are my further concerns:

Basically, these are the previous ITEMS I didn't check as it was stated to be created a new ticket/branch: Items 5, 10, 11, 12, 13, 14 (take note I used the term item because there's a case that an image I sent will be associated with 2 items but with different issue/scenario like items 8 and 9)

1. i1: first concern was already good but the moment I save any elementary stream then update it, I can proceed on updating without any PID value. 
2. i2: this was my previous 4th concern and it's still closing even on clicking outside modal.
3. i3: clicking cancel or close button can now go back to add program modal but clicking the prev button should go back to "add elementary stream modal".
4. i4: any values on the add elementary stream modal will now be removed after clicking cancel but still retained when clicking the X button above.
5. language dropdown order is still different from clientapp (this was one of the mentioned fix but still persist)

i1: 
image

i2: 
image

i3: 
image

i4: 
image

**Comment by triveni-codev** [comment]
Merging this PR to start a fresh branch with the review comments to apply as mentioned in https://github.com/triveni-codev/GBWebApp-dev/pull/449#pullrequestreview-1064419129.

This PR covers PSIP-Terrestrial -> Elementary Streams, Dirty change handling and Big Commit.

Cheers for team synergy.


~~~~
PSIP-Cable/Terrestrial Type: Refinement of Elementary Stream(s) Dirty Change handling and "Big Commit" development
https://app.asana.com/0/1202364707885489/1202626000178737/f

**Pull request merged**
