### PR TITLE
chrisdev_transportExport_1203106518351865

### PR DESCRIPTION
**Pull request by chriscodev**
ASANA TICKET: Transports Section Development: Export feature
https://app.asana.com/0/1203106518351809/1203106518351865

Note:
Web page does not support Save As window, when clicking export CSV it does directly download the file containing the values in the elementary Stream.

### CODE REVIEW

**Comment by darlp5589** [comment]
Will check on this.

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Checked on this and got an error on the 

1. i1: I got an error when I clicked on the export button above the table. If that is not used, maybe we can remove it?
2. i2: Exported any of the transports but I can't see any values being pulled by opening in both Excel and in VSCode. Compared with Java App that has.
3. Is there a way, we can set a filename just like in Java App? Currently it's download.csv.


i1: 
image

i2: 
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Checked and here are my concerns:

i1: I have created a Transport with elementary streams already then exported that Transport into a CSV file and opened in Excel. I am doing this on both Java and Client App for the same Transport. You can see there are differences in values on both platforms. Angular App also has extra record being added and the values of columns PMTPID(I)(O) and PCRPID(I)(O) seemed interchanged.
i2: I have exported a Transport (w/o elementary streams) on both platforms and that is how they look like. Java App has values while Angular App is empty.


i1: 
image

i2: 
image

**Review by darlp5589 — CHANGES_REQUESTED** [review]
Done checking. They still have different values.

i1: Transport with Elementary Streams
i2: Transport with Program but no Elementary Streams
i3: Transport w/o a Program

i1: 
image

i2: 
image

i3: 
image

**Comment by chriscodev** [comment]
Hi @darlp5589 , you may now verify on your end.

i1: Transport with Elementary Streams 
**DONE** - updated code to use shortName

i2: Transport with Program but no Elementary Streams
**DONE** - updated code 

i3: Transport w/o a Program
**DONE** - updated code 

Cheers,
Christian

**Review by darlp5589 — APPROVED** [review]
LGTM!

**Comment by triveni-codev** [comment]
Tian,

1) Kindly apply a coding convention update to your btnExportTransport(rowData) method. Can be on your final import PR since this has a PR link towards it. 
Regarding
a) spacing in conditional if-else blocks
b) spacing in comparison and logical operators
c) Checking-related console logs that could be removed
d) Single zone mini lintings

2) Kindly assess & break down the flow inside btnExportTransport(rowData) method to individually-dedicated mini functions (each mini function containing one dedicated purpose/task) for abstraction. Can be on your final import PR since this has a PR link towards it.

Commencing merge.


~~~
Transports Section Development: Export feature
https://app.asana.com/0/1203106518351809/1203106518351865

**Pull request merged**
